version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      go-modules:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      container-images:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      github-actions-updates:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      web-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /test/browser
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      browser-test-dependencies:
        patterns:
          - "*"
