// Code generated by scripts/generate-go-sdk-streaming.py; DO NOT EDIT.

package veilclient

import (
	"context"
	"errors"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// StreamingResponse exposes status and headers without buffering the body.
type StreamingResponse struct {
	StatusCode int
	Header     http.Header
	Body       io.ReadCloser
}

// GetApiBackupsNameDownloadStream downloads a backup without JSON decoding or
// buffering. The caller owns Body and must close it.
func (c *Client) GetApiBackupsNameDownloadStream(ctx context.Context, name BackupName, reqEditors ...RequestEditorFn) (*StreamingResponse, error) {
	endpoint, err := resolveRelativeURL(c.Server, "api/backups/"+url.PathEscape(string(name))+"/download")
	if err != nil {
		return nil, err
	}
	request, err := http.NewRequestWithContext(ctx, http.MethodGet, endpoint.String(), nil)
	if err != nil {
		return nil, err
	}
	if err := c.applyEditors(ctx, request, reqEditors); err != nil {
		return nil, err
	}
	response, err := c.Client.Do(request)
	if err != nil {
		return nil, err
	}
	if response.Body == nil {
		return nil, errors.New("streaming response has no body")
	}
	return &StreamingResponse{StatusCode: response.StatusCode, Header: response.Header.Clone(), Body: response.Body}, nil
}

// resolveRelativeURL rejects absolute and root-relative operation input so a
// configured server base path can never be silently replaced.
func resolveRelativeURL(server, apiPath string) (*url.URL, error) {
	base, err := url.Parse(server)
	if err != nil || !base.IsAbs() || base.Host == "" {
		return nil, errors.New("invalid API server URL")
	}
	operation, err := url.Parse(apiPath)
	if err != nil {
		return nil, err
	}
	if operation.IsAbs() || operation.Host != "" || strings.HasPrefix(apiPath, "/") || strings.HasPrefix(apiPath, "//") {
		return nil, errors.New("absolute API path is not allowed")
	}
	if !strings.HasSuffix(base.Path, "/") {
		base.Path += "/"
	}
	return base.ResolveReference(operation), nil
}
