package api

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/mikkelchokolate/Veil/internal/audit"
	"github.com/mikkelchokolate/Veil/internal/client"
)

// registerClientV1Routes registers the normalized client management endpoints
// (Stage 1). These operate on the Client domain model, never on
// inbound-embedded profiles.
func (s *managementState) registerClientV1Routes(mux *http.ServeMux) {
	mux.HandleFunc("/api/v1/clients", s.handleV1Clients)
	mux.HandleFunc("/api/v1/clients/bulk", s.handleV1Bulk)
	mux.HandleFunc("/api/v1/clients/migrate-legacy", s.handleV1MigrateLegacy)
	mux.HandleFunc("/api/v1/clients/", s.handleV1ClientByID)
}

// clientsV1Enabled reports whether the normalized store is available.
func (s *managementState) clientsV1Enabled(w http.ResponseWriter) bool {
	if s.clientService == nil {
		writeError(w, "client store unavailable", http.StatusServiceUnavailable)
		return false
	}
	return true
}

// --- request/response DTOs ---

type v1CreateClientRequest struct {
	Name             string  `json:"name"`
	Email            *string `json:"email"`
	Enabled          *bool   `json:"enabled"`
	GroupID          *string `json:"groupId"`
	QuotaBytes       *int64  `json:"quotaBytes"`
	QuotaResetPolicy string  `json:"quotaResetPolicy"`
	QuotaResetAt     *int64  `json:"quotaResetAt"`
	ExpiresAt        *int64  `json:"expiresAt"`
	DeviceLimit      *int    `json:"deviceLimit"`
	Notes            string  `json:"notes"`
	// Bind the client to inbounds at creation time. For each entry a credential
	// may be provided; otherwise one is generated by the caller-side flow.
	Bindings []v1BindingRequest `json:"bindings"`
}

type v1BindingRequest struct {
	InboundID       string `json:"inboundId"`
	RuntimeIdentity string `json:"runtimeIdentity"`
	Credential      string `json:"credential"`
	Enabled         *bool  `json:"enabled"`
}

type patchField[T any] struct {
	Present bool
	Null    bool
	Value   T
}

func (f *patchField[T]) UnmarshalJSON(body []byte) error {
	f.Present = true
	if bytes.Equal(bytes.TrimSpace(body), []byte("null")) {
		f.Null = true
		var zero T
		f.Value = zero
		return nil
	}
	f.Null = false
	return json.Unmarshal(body, &f.Value)
}

type v1PatchClientRequest struct {
	Version          int                `json:"version"`
	Name             patchField[string] `json:"name"`
	Email            patchField[string] `json:"email"`
	Enabled          patchField[bool]   `json:"enabled"`
	GroupID          patchField[string] `json:"groupId"`
	QuotaBytes       patchField[int64]  `json:"quotaBytes"`
	QuotaResetPolicy patchField[string] `json:"quotaResetPolicy"`
	QuotaResetAt     patchField[int64]  `json:"quotaResetAt"`
	ExpiresAt        patchField[int64]  `json:"expiresAt"`
	DeviceLimit      patchField[int]    `json:"deviceLimit"`
	Notes            patchField[string] `json:"notes"`
}

func optionalStringPatch(field patchField[string]) *string {
	if field.Null {
		return nil
	}
	value := field.Value
	return &value
}

func optionalInt64Patch(field patchField[int64]) *int64 {
	if field.Null {
		return nil
	}
	value := field.Value
	return &value
}

func optionalIntPatch(field patchField[int]) *int {
	if field.Null {
		return nil
	}
	value := field.Value
	return &value
}

func (s *managementState) handleV1Clients(w http.ResponseWriter, r *http.Request) {
	if !s.clientsV1Enabled(w) {
		return
	}
	switch r.Method {
	case http.MethodGet:
		s.handleV1ListClients(w, r)
	case http.MethodPost:
		s.handleV1CreateClient(w, r)
	default:
		methodNotAllowed(w, http.MethodGet, http.MethodPost)
	}
}

// --- Bulk operations ---

type v1BulkRequest struct {
	Action     string   `json:"action"` // enable|disable|delete|extend_expiry|set_quota|reset_traffic|attach_inbound|detach_inbound
	ClientIDs  []string `json:"clientIds"`
	Days       *int     `json:"days"`       // for extend_expiry
	QuotaBytes *int64   `json:"quotaBytes"` // for set_quota
	InboundID  string   `json:"inboundId"`  // for attach/detach_inbound
}

type v1BulkResult struct {
	ID      string `json:"id"`
	OK      bool   `json:"ok"`
	Message string `json:"message,omitempty"`
}

// handleV1Bulk applies one action to many clients. Per-client failures roll
// back only that client (SQLite savepoints inside ONE transaction); the whole
// bulk then commits atomically together with the desired-revision bump and the
// immutable snapshot, and exactly one apply job runs. When nothing was
// actually applied (all failed or skipped), no revision is created at all.
func (s *managementState) handleV1Bulk(w http.ResponseWriter, r *http.Request) {
	if !s.clientsV1Enabled(w) {
		return
	}
	if r.Method != http.MethodPost {
		methodNotAllowed(w, http.MethodPost)
		return
	}
	var req v1BulkRequest
	if !decodeJSONRequest(w, r, &req) {
		return
	}
	if req.Action == "" || len(req.ClientIDs) == 0 {
		writeError(w, "action and clientIds are required", http.StatusBadRequest)
		return
	}
	results := make([]v1BulkResult, 0, len(req.ClientIDs))
	succeeded := 0
	skipped := 0
	outcome, err := s.withClientMutation(r, actorFromRequest(r), func(tx *client.Tx) error {
		anyApplied := false
		for i, id := range req.ClientIDs {
			sp := fmt.Sprintf("bulk_%d", i)
			if err := tx.Savepoint(sp); err != nil {
				return err
			}
			res := v1BulkResult{ID: id}
			ok, sk, aerr := s.applyBulkActionTx(tx, id, req)
			switch {
			case aerr != nil:
				_ = tx.RollbackToSavepoint(sp)
				res.OK = false
				res.Message = aerr.Error()
			case sk:
				_ = tx.RollbackToSavepoint(sp)
				res.OK = false
				res.Message = "skipped"
				skipped++
			default:
				if err := tx.ReleaseSavepoint(sp); err != nil {
					return err
				}
				res.OK = ok
				succeeded++
				anyApplied = true
			}
			results = append(results, res)
		}
		if !anyApplied {
			// Nothing changed: roll the (empty) transaction back and skip the
			// revision bump + apply entirely.
			return errNoClientChanges
		}
		return nil
	})
	failed := len(req.ClientIDs) - succeeded - skipped
	s.logUserAction(r, "bulk_"+req.Action, "clients", err == nil && succeeded == len(req.ClientIDs), "")
	if err != nil {
		s.writeV1ClientError(w, err)
		return
	}
	resp := map[string]any{
		"action":    req.Action,
		"total":     len(req.ClientIDs),
		"succeeded": succeeded,
		"skipped":   skipped,
		"failed":    failed,
		"results":   results,
	}
	s.mergeOutcomeInto(resp, outcome)
	writeJSON(w, resp)
}

// errNoClientChanges signals from a mutation closure that no change was
// actually applied (e.g. a bulk where every client failed or was skipped):
// the transaction rolls back and NO revision/snapshot/apply is recorded.
var errNoClientChanges = errors.New("no client changes applied")

// applyBulkActionTx applies one bulk action to one client inside the bulk
// transaction. Returns (applied, skipped, err) with the same semantics as the
// former autocommit variant.
func (s *managementState) applyBulkActionTx(tx *client.Tx, id string, req v1BulkRequest) (bool, bool, error) {
	existing, err := tx.Get(id)
	if err != nil {
		return false, false, err
	}
	c := existing
	switch req.Action {
	case "enable":
		c.Enabled = true
	case "disable":
		c.Enabled = false
	case "delete":
		return true, false, tx.Delete(id)
	case "reset_quota":
		// Deprecated alias of reset_traffic kept for backward compatibility.
		fallthrough
	case "reset_traffic":
		// Clear actual recorded usage and the depleted flag. This is the
		// honest "reset traffic" (not merely un-depleting the client).
		if err := tx.ResetTrafficForClient(id); err != nil {
			return false, false, err
		}
		c.Depleted = false
		c.QuotaResetAt = nil
	case "set_quota":
		if req.QuotaBytes == nil || *req.QuotaBytes < 0 || *req.QuotaBytes > client.MaxQuotaBytes {
			return false, false, client.ErrValidation
		}
		c.QuotaBytes = req.QuotaBytes
		bindings, err := tx.BindingsForClient(id)
		if err != nil {
			return false, false, err
		}
		if err := s.validateQuotaBindingsLocked(c.QuotaBytes, bindings); err != nil {
			return false, false, err
		}
	case "extend", "extend_expiry":
		if req.Days == nil || *req.Days <= 0 {
			return false, false, client.ErrValidation
		}
		var base int64
		now := nowUnixAPI()
		if c.ExpiresAt != nil && *c.ExpiresAt > now {
			base = *c.ExpiresAt
		} else {
			base = now
		}
		newExp := base + int64(*req.Days)*86400
		c.ExpiresAt = &newExp
	case "attach_inbound":
		if req.InboundID == "" {
			return false, false, client.ErrValidation
		}
		if err := s.validateQuotaBindingsLocked(c.QuotaBytes, []client.Binding{{InboundID: req.InboundID, Enabled: true}}); err != nil {
			return false, false, err
		}
		if _, err := s.clientService.AddBindingTx(tx, id, req.InboundID); err != nil {
			return false, false, err
		}
		return true, false, nil
	case "detach_inbound":
		if req.InboundID == "" {
			return false, false, client.ErrValidation
		}
		bv, err := tx.BindingsForClient(id)
		if err != nil {
			return false, false, err
		}
		for _, b := range bv {
			if b.InboundID == req.InboundID {
				return true, false, s.clientService.RemoveBindingTx(tx, b.ID, id)
			}
		}
		return false, true, nil // not attached -> skipped
	default:
		return false, false, client.ErrValidation
	}
	_, err = tx.Update(c, c.Version)
	return err == nil, false, err
}

// handleV1MigrateLegacy converts legacy inbound-embedded client profiles into
// the normalized Client+Binding+Credential model. It is idempotent (stable
// derived client IDs) so it is safe to re-run during a rolling migration. After
// migrating, the operator can drop the embedded profiles; normalized clients
// are rendered into live configs regardless.
func (s *managementState) handleV1MigrateLegacy(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		methodNotAllowed(w, http.MethodPost)
		return
	}
	if s.clientMigrator == nil {
		writeError(w, "client migration unavailable", http.StatusServiceUnavailable)
		return
	}
	s.mu.Lock()
	inbounds := append([]Inbound(nil), s.inbounds...)
	s.mu.Unlock()

	type inboundResult struct {
		Inbound            string `json:"inbound"`
		ClientsCreated     int    `json:"clientsCreated"`
		BindingsCreated    int    `json:"bindingsCreated"`
		CredentialsCreated int    `json:"credentialsCreated"`
		Skipped            int    `json:"skipped"`
	}
	s.logUserAction(r, "migrate_legacy", "", true, "")
	results := []inboundResult{}
	totalCreated := 0
	outcome, err := s.withClientMutation(r, actorFromRequest(r), func(tx *client.Tx) error {
		anyApplied := false
		for _, in := range inbounds {
			if len(in.Profiles) == 0 {
				continue
			}
			profiles := make([]client.LegacyProfile, 0, len(in.Profiles))
			for _, p := range in.Profiles {
				profiles = append(profiles, client.LegacyProfile{
					Name: p.Name, Username: p.Username, Password: p.Password, Enabled: p.Enabled,
				})
			}
			res, err := s.clientMigrator.MigrateInboundProfilesTx(tx, in.Name, in.Protocol, profiles)
			if err != nil {
				return fmt.Errorf("migrate inbound %s: %w", in.Name, err)
			}
			totalCreated += res.ClientsCreated
			if res.ClientsCreated > 0 {
				anyApplied = true
			}
			results = append(results, inboundResult{
				Inbound:            in.Name,
				ClientsCreated:     res.ClientsCreated,
				BindingsCreated:    res.BindingsCreated,
				CredentialsCreated: res.CredentialsCreated,
				Skipped:            res.Skipped,
			})
		}
		if !anyApplied {
			// Everything already migrated (idempotent re-run): no revision.
			return errNoClientChanges
		}
		return nil
	})
	if err != nil {
		s.writeV1ClientError(w, err)
		return
	}
	s.writeMutationResponse(w, http.StatusOK, map[string]any{
		"results":        results,
		"clientsCreated": totalCreated,
	}, outcome)
}

func nowUnixAPI() int64 { return time.Now().Unix() }

// actorFromRequest extracts the authenticated username for audit/apply actor.
func actorFromRequest(r *http.Request) string {
	actor, _ := r.Context().Value(contextKeyUsername).(string)
	return actor
}

func (s *managementState) handleV1ListClients(w http.ResponseWriter, r *http.Request) {
	q := r.URL.Query()
	f := client.ListFilter{
		Page:       atoiDefault(q.Get("page"), 1),
		PageSize:   atoiDefault(q.Get("pageSize"), 25),
		Search:     q.Get("search"),
		Status:     q.Get("status"),
		InboundID:  q.Get("inboundId"),
		GroupID:    q.Get("groupId"),
		QuotaState: q.Get("quotaState"),
		Sort:       q.Get("sort"),
	}
	if f.PageSize > 100 {
		f.PageSize = 100
	}
	if v := q.Get("expiresBefore"); v != "" {
		if ts, err := strconv.ParseInt(v, 10, 64); err == nil {
			f.ExpiresBefore = &ts
		}
	}
	if v := q.Get("expiresAfter"); v != "" {
		if ts, err := strconv.ParseInt(v, 10, 64); err == nil {
			f.ExpiresAfter = &ts
		}
	}
	items, total, err := s.clientService.List(f)
	if err != nil {
		writeError(w, err.Error(), http.StatusInternalServerError)
		return
	}
	writeJSON(w, map[string]any{"items": items, "total": total, "page": f.Page, "pageSize": f.PageSize})
}

func (s *managementState) quotaSupportedForInboundLocked(inboundID string) bool {
	for _, inbound := range s.inbounds {
		if inbound.Name == inboundID {
			return inbound.Enabled && inbound.Protocol == "hysteria2"
		}
	}
	return false
}

func (s *managementState) validateQuotaBindingsLocked(quota *int64, bindings []client.Binding) error {
	if quota == nil {
		return nil
	}
	for _, binding := range bindings {
		if binding.Enabled && !s.quotaSupportedForInboundLocked(binding.InboundID) {
			return fmt.Errorf("%w: quota enforcement is unsupported for inbound %s", client.ErrValidation, binding.InboundID)
		}
	}
	return nil
}

func (s *managementState) handleV1CreateClient(w http.ResponseWriter, r *http.Request) {
	var req v1CreateClientRequest
	if !decodeJSONRequest(w, r, &req) {
		return
	}
	if req.DeviceLimit != nil {
		writeError(w, "deviceLimit is unsupported until protocol-aware connection enforcement is available", http.StatusBadRequest)
		return
	}
	enabled := true
	if req.Enabled != nil {
		enabled = *req.Enabled
	}
	c := client.Client{
		ID:               uuid.NewString(),
		Name:             req.Name,
		Email:            req.Email,
		Enabled:          enabled,
		GroupID:          req.GroupID,
		QuotaBytes:       req.QuotaBytes,
		QuotaResetPolicy: req.QuotaResetPolicy,
		QuotaResetAt:     req.QuotaResetAt,
		ExpiresAt:        req.ExpiresAt,
		DeviceLimit:      req.DeviceLimit,
		Notes:            req.Notes,
	}
	// A4/A5 + blocker A1: single SQL transaction. Client + bindings +
	// credentials + desired-revision bump + immutable snapshot commit or roll
	// back atomically; exactly one apply runs for the fully-configured client;
	// no compensating deletes. A failure returns an error, never a 201 for a
	// partially-created client.
	bindings := make([]client.BindingInput, 0, len(req.Bindings))
	for _, b := range req.Bindings {
		if b.InboundID == "" {
			continue
		}
		if !s.bindingInboundExists(b.InboundID) {
			writeError(w, "binding inbound does not exist", http.StatusBadRequest)
			return
		}
		bindings = append(bindings, client.BindingInput{InboundID: b.InboundID, RuntimeIdentity: b.RuntimeIdentity, Credential: b.Credential, Enabled: b.Enabled})
	}
	var createdID string
	var issued []client.IssuedCredential
	outcome, err := s.withClientMutation(r, actorFromRequest(r), func(tx *client.Tx) error {
		for _, binding := range bindings {
			if !s.bindingInboundExistsLocked(binding.InboundID) {
				return fmt.Errorf("%w: binding inbound does not exist", client.ErrValidation)
			}
		}
		prospective := make([]client.Binding, 0, len(bindings))
		for _, binding := range bindings {
			enabled := true
			if binding.Enabled != nil {
				enabled = *binding.Enabled
			}
			prospective = append(prospective, client.Binding{InboundID: binding.InboundID, Enabled: enabled})
		}
		if err := s.validateQuotaBindingsLocked(c.QuotaBytes, prospective); err != nil {
			return err
		}
		id, iss, err := s.clientService.CreateWithBindingsIssuedTx(tx, c, bindings)
		if err != nil {
			return err
		}
		createdID, issued = id, iss
		return nil
	})
	if err != nil {
		s.logUserAction(r, "create_client", c.ID, false, err.Error())
		s.writeV1ClientError(w, err)
		return
	}
	s.logUserAction(r, "create_client", createdID, true, "")
	// Build the response view after commit (outside the mutation lock).
	final, err := s.clientService.Get(createdID)
	if err != nil {
		s.writeV1ClientError(w, err)
		return
	}
	// S2: response shape { client, issuedCredentials, revision, applyJob,
	// success }. The generated plaintext appears exactly once here; it is
	// never persisted (only the encrypted form is stored).
	resp := map[string]any{"client": final}
	if len(issued) > 0 {
		resp["issuedCredentials"] = issued
		markIdempotencySecretResponse(w, createdID, 1)
	}
	s.mergeOutcomeInto(resp, outcome)
	writeJSONStatus(w, http.StatusCreated, resp)
}

func (s *managementState) handleV1ClientByID(w http.ResponseWriter, r *http.Request) {
	if !s.clientsV1Enabled(w) {
		return
	}
	rest := strings.TrimPrefix(r.URL.Path, "/api/v1/clients/")
	parts := strings.Split(rest, "/")
	id := parts[0]
	if id == "" {
		writeNotFound(w)
		return
	}
	// Sub-resources: /api/v1/clients/{id}/bindings, /credentials, /subscription...
	if len(parts) > 1 {
		s.handleV1ClientSubresource(w, r, id, parts[1:])
		return
	}
	switch r.Method {
	case http.MethodGet:
		view, err := s.clientService.Get(id)
		if err != nil {
			writeNotFound(w)
			return
		}
		writeJSON(w, view)
	case http.MethodPatch:
		s.handleV1UpdateClient(w, r, id)
	case http.MethodDelete:
		outcome, err := s.withClientMutation(r, actorFromRequest(r), func(tx *client.Tx) error {
			return s.clientService.DeleteTx(tx, id)
		})
		if err != nil {
			s.writeV1ClientError(w, err)
			return
		}
		s.logUserAction(r, "delete_client", id, true, "")
		s.writeMutationResponse(w, http.StatusOK, map[string]string{"id": id}, outcome)
	default:
		methodNotAllowed(w, http.MethodGet, http.MethodPatch, http.MethodDelete)
	}
}

func (s *managementState) handleV1UpdateClient(w http.ResponseWriter, r *http.Request, id string) {
	var req v1PatchClientRequest
	if !decodeJSONRequest(w, r, &req) {
		return
	}
	if req.DeviceLimit.Present && !req.DeviceLimit.Null {
		writeError(w, "deviceLimit is unsupported until protocol-aware connection enforcement is available", http.StatusBadRequest)
		return
	}
	existing, err := s.clientService.Get(id)
	if err != nil {
		writeNotFound(w)
		return
	}
	c := existing.Client
	if req.Name.Present {
		c.Name = req.Name.Value
	}
	if req.Email.Present {
		c.Email = optionalStringPatch(req.Email)
	}
	if req.Enabled.Present {
		c.Enabled = !req.Enabled.Null && req.Enabled.Value
	}
	if req.GroupID.Present {
		c.GroupID = optionalStringPatch(req.GroupID)
	}
	if req.QuotaBytes.Present {
		c.QuotaBytes = optionalInt64Patch(req.QuotaBytes)
	}
	if req.QuotaResetPolicy.Present {
		if req.QuotaResetPolicy.Null {
			c.QuotaResetPolicy = client.ResetNever
		} else {
			c.QuotaResetPolicy = req.QuotaResetPolicy.Value
		}
	}
	if req.QuotaResetAt.Present {
		c.QuotaResetAt = optionalInt64Patch(req.QuotaResetAt)
	}
	if req.ExpiresAt.Present {
		c.ExpiresAt = optionalInt64Patch(req.ExpiresAt)
	}
	if req.DeviceLimit.Present {
		c.DeviceLimit = optionalIntPatch(req.DeviceLimit)
	}
	if req.Notes.Present {
		if req.Notes.Null {
			c.Notes = ""
		} else {
			c.Notes = req.Notes.Value
		}
	}
	updated, err := s.withClientMutation(r, actorFromRequest(r), func(tx *client.Tx) error {
		bindings, err := tx.BindingsForClient(id)
		if err != nil {
			return err
		}
		if err := s.validateQuotaBindingsLocked(c.QuotaBytes, bindings); err != nil {
			return err
		}
		return s.clientService.UpdateTx(tx, c, req.Version)
	})
	if err != nil {
		s.logUserAction(r, "update_client", id, false, err.Error())
		s.writeV1ClientError(w, err)
		return
	}
	s.logUserAction(r, "update_client", id, true, "")
	// Build the response view after commit (outside the mutation lock).
	updatedView, err := s.clientService.Get(id)
	if err != nil {
		s.writeV1ClientError(w, err)
		return
	}
	s.writeMutationResponse(w, http.StatusOK, updatedView, updated)
}

func (s *managementState) handleV1ClientSubresource(w http.ResponseWriter, r *http.Request, clientID string, parts []string) {
	switch parts[0] {
	case "audit":
		s.handleV1ClientAudit(w, r, clientID)
	case "bindings":
		s.handleV1ClientBindings(w, r, clientID, parts)
	case "credentials":
		s.handleV1ClientCredentials(w, r, clientID, parts)
	case "links":
		s.handleV1ClientLinks(w, r, clientID)
	case "tokens":
		if len(parts) == 1 {
			s.handleV1ClientTokens(w, r, clientID)
			return
		}
		// /tokens/{tokenId} or /tokens/{tokenId}/rotate
		tokenID := parts[1]
		action := ""
		if len(parts) > 2 {
			action = parts[2]
		}
		s.handleV1ClientTokenByID(w, r, clientID, tokenID, action)
	default:
		writeNotFound(w)
	}
}

// handleV1ClientAudit returns the audit entries scoped to one client. Entries
// match when the audit target is the client's ID, its current name, or a
// client-scoped action whose target is this client. Admin-only, newest first.
func (s *managementState) handleV1ClientAudit(w http.ResponseWriter, r *http.Request, clientID string) {
	if r.Method != http.MethodGet {
		methodNotAllowed(w, http.MethodGet)
		return
	}
	if !requestHasAdminRole(s, r) {
		writeError(w, "forbidden: admin role required", http.StatusForbidden)
		return
	}
	view, err := s.clientService.Get(clientID)
	if err != nil {
		writeNotFound(w)
		return
	}
	records, err := s.auditRecorder().List(500, time.Time{})
	if err != nil {
		writeError(w, "failed to read audit history", http.StatusInternalServerError)
		return
	}
	items := make([]audit.Record, 0)
	for _, rec := range records {
		// Client-scoped actions record the target as the client ID (mutations)
		// or the client name (create). Bindings/credentials record the client
		// ID as target with the sub-id in details.
		if rec.Target == clientID || rec.Target == view.Name {
			items = append(items, rec)
		}
	}
	writeJSON(w, map[string]any{"items": items})
}

func (s *managementState) bindingInboundExists(inboundID string) bool {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.bindingInboundExistsLocked(inboundID)
}

func (s *managementState) bindingInboundExistsLocked(inboundID string) bool {
	for _, inbound := range s.inbounds {
		if inbound.Name == inboundID {
			return true
		}
	}
	return false
}

func (s *managementState) handleV1ClientBindings(w http.ResponseWriter, r *http.Request, clientID string, parts []string) {
	if len(parts) == 1 { // /bindings
		if r.Method == http.MethodPost {
			var req v1BindingRequest
			if !decodeJSONRequest(w, r, &req) {
				return
			}
			if !s.bindingInboundExists(req.InboundID) {
				writeError(w, "binding inbound does not exist", http.StatusBadRequest)
				return
			}
			var b client.Binding
			outcome, err := s.withClientMutation(r, actorFromRequest(r), func(tx *client.Tx) error {
				if !s.bindingInboundExistsLocked(req.InboundID) {
					return fmt.Errorf("%w: binding inbound does not exist", client.ErrValidation)
				}
				existingClient, err := tx.Get(clientID)
				if err != nil {
					return err
				}
				enabled := true
				if req.Enabled != nil {
					enabled = *req.Enabled
				}
				if err := s.validateQuotaBindingsLocked(existingClient.QuotaBytes, []client.Binding{{InboundID: req.InboundID, Enabled: enabled}}); err != nil {
					return err
				}
				nb, err := s.clientService.AddBindingWithIdentityEnabledTx(tx, clientID, req.InboundID, req.RuntimeIdentity, enabled)
				if err != nil {
					return err
				}
				b = nb
				if req.Credential != "" {
					// The credential joins the SAME transaction: a binding is
					// never committed without its credential (the former code
					// swallowed this error entirely).
					if _, err := s.clientService.SetCredentialTx(tx, b.ID, "password", req.Credential); err != nil {
						return err
					}
				}
				return nil
			})
			if err != nil {
				s.writeV1ClientError(w, err)
				return
			}
			s.logUserAction(r, "add_binding", clientID, true, req.InboundID)
			s.writeMutationResponse(w, http.StatusCreated, b, outcome)
			return
		}
		methodNotAllowed(w, http.MethodPost)
		return
	}
	// /bindings/{bindingId}
	bindingID := parts[1]
	if r.Method == http.MethodPatch {
		var req struct {
			Enabled *bool `json:"enabled"`
			Version int   `json:"version"`
		}
		if !decodeJSONRequest(w, r, &req) {
			return
		}
		if req.Enabled == nil {
			writeError(w, "enabled is required", http.StatusBadRequest)
			return
		}
		var b client.Binding
		outcome, err := s.withClientMutation(r, actorFromRequest(r), func(tx *client.Tx) error {
			currentBinding, err := tx.GetBinding(bindingID)
			if err != nil {
				return err
			}
			if currentBinding.ClientID != clientID {
				return client.ErrNotFound
			}
			if *req.Enabled {
				existingClient, err := tx.Get(currentBinding.ClientID)
				if err != nil {
					return err
				}
				if err := s.validateQuotaBindingsLocked(existingClient.QuotaBytes, []client.Binding{{InboundID: currentBinding.InboundID, Enabled: true}}); err != nil {
					return err
				}
			}
			ub, err := s.clientService.SetBindingEnabledTx(tx, bindingID, *req.Enabled, req.Version)
			if err != nil {
				return err
			}
			b = ub
			return nil
		})
		if err != nil {
			s.writeV1ClientError(w, err)
			return
		}
		s.logUserAction(r, "update_binding", clientID, true, bindingID)
		s.writeMutationResponse(w, http.StatusOK, b, outcome)
		return
	}
	if r.Method == http.MethodDelete {
		outcome, err := s.withClientMutation(r, actorFromRequest(r), func(tx *client.Tx) error {
			binding, err := tx.GetBinding(bindingID)
			if err != nil {
				return err
			}
			if binding.ClientID != clientID {
				return client.ErrNotFound
			}
			return s.clientService.RemoveBindingTx(tx, bindingID, clientID)
		})
		if err != nil {
			s.writeV1ClientError(w, err)
			return
		}
		s.logUserAction(r, "remove_binding", clientID, true, bindingID)
		s.writeMutationResponse(w, http.StatusOK, map[string]string{"id": bindingID}, outcome)
		return
	}
	methodNotAllowed(w, http.MethodPatch, http.MethodDelete)
}

func (s *managementState) handleV1ClientCredentials(w http.ResponseWriter, r *http.Request, clientID string, parts []string) {
	// /credentials/{bindingId} with POST {kind,value} to set; POST .../rotate to rotate.
	if len(parts) < 2 {
		writeNotFound(w)
		return
	}
	bindingID := parts[1]
	if r.Method == http.MethodPost && len(parts) == 2 {
		var req struct {
			Kind  string `json:"kind"`
			Value string `json:"value"`
		}
		if !decodeJSONRequest(w, r, &req) {
			return
		}
		if req.Kind == "" {
			req.Kind = "password"
		}
		var cred client.Credential
		outcome, err := s.withClientMutation(r, actorFromRequest(r), func(tx *client.Tx) error {
			binding, err := tx.GetBinding(bindingID)
			if err != nil {
				return err
			}
			if binding.ClientID != clientID {
				return client.ErrNotFound
			}
			nc, err := s.clientService.SetCredentialTx(tx, bindingID, req.Kind, req.Value)
			if err != nil {
				return err
			}
			cred = nc
			return nil
		})
		if err != nil {
			s.writeV1ClientError(w, err)
			return
		}
		s.logUserAction(r, "set_credential", clientID, true, bindingID)
		s.writeMutationResponse(w, http.StatusCreated, cred, outcome)
		return
	}
	if r.Method == http.MethodPost && len(parts) == 3 && parts[2] == "rotate" {
		var req struct {
			Kind  string `json:"kind"`
			Value string `json:"value"`
		}
		if !decodeJSONRequest(w, r, &req) {
			return
		}
		if req.Kind == "" {
			req.Kind = "password"
		}
		// Server-generated rotate (preferred, capability-driven): when no value
		// is supplied the server generates a high-entropy secret and returns it
		// exactly once. An explicit value keeps the legacy caller-supplied path.
		if req.Value == "" {
			var gen client.GeneratedCredential
			outcome, err := s.withClientMutation(r, actorFromRequest(r), func(tx *client.Tx) error {
				binding, err := tx.GetBinding(bindingID)
				if err != nil {
					return err
				}
				if binding.ClientID != clientID {
					return client.ErrNotFound
				}
				g, err := s.clientService.RotateCredentialGeneratedTx(tx, bindingID, req.Kind)
				if err != nil {
					return err
				}
				gen = g
				return nil
			})
			if err != nil {
				s.writeV1ClientError(w, err)
				return
			}
			s.logUserAction(r, "rotate_credential", clientID, true, bindingID)
			markIdempotencySecretResponse(w, bindingID, uint64(gen.Credential.CredentialVersion))
			s.writeMutationResponse(w, http.StatusOK, gen, outcome)
			return
		}
		var cred client.Credential
		outcome, err := s.withClientMutation(r, actorFromRequest(r), func(tx *client.Tx) error {
			binding, err := tx.GetBinding(bindingID)
			if err != nil {
				return err
			}
			if binding.ClientID != clientID {
				return client.ErrNotFound
			}
			nc, err := s.clientService.RotateCredentialTx(tx, bindingID, req.Kind, req.Value)
			if err != nil {
				return err
			}
			cred = nc
			return nil
		})
		if err != nil {
			s.writeV1ClientError(w, err)
			return
		}
		s.logUserAction(r, "rotate_credential", clientID, true, bindingID)
		s.writeMutationResponse(w, http.StatusOK, cred, outcome)
		return
	}
	writeNotFound(w)
}

// writeV1ClientError maps domain errors to HTTP status codes honestly.
func (s *managementState) writeV1ClientError(w http.ResponseWriter, err error) {
	switch {
	case errors.Is(err, client.ErrNotFound), errors.Is(err, client.ErrSecretUnavailable):
		writeError(w, err.Error(), http.StatusNotFound)
	case errors.Is(err, client.ErrVersionConflict):
		writeError(w, err.Error(), http.StatusConflict)
	case errors.Is(err, client.ErrDuplicateBinding):
		writeError(w, err.Error(), http.StatusConflict)
	case errors.Is(err, client.ErrValidation):
		writeError(w, err.Error(), http.StatusBadRequest)
	default:
		writeError(w, err.Error(), http.StatusInternalServerError)
	}
}

func atoiDefault(s string, def int) int {
	if s == "" {
		return def
	}
	n, err := strconv.Atoi(s)
	if err != nil || n < 1 {
		return def
	}
	return n
}

var _ = json.Marshal
