package api

import (
	"encoding/json"
	"errors"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/mikkelchokolate/Veil/internal/client"
)

// registerClientV1Routes registers the normalized client management endpoints
// (Stage 1). These operate on the Client domain model, never on
// inbound-embedded profiles.
func (s *managementState) registerClientV1Routes(mux *http.ServeMux) {
	mux.HandleFunc("/api/v1/clients", s.handleV1Clients)
	mux.HandleFunc("/api/v1/clients/bulk", s.handleV1Bulk)
	mux.HandleFunc("/api/v1/clients/migrate-legacy", s.handleV1MigrateLegacy)
	mux.HandleFunc("/api/v1/clients/", s.handleV1ClientByID)
}

// clientsV1Enabled reports whether the normalized store is available.
func (s *managementState) clientsV1Enabled(w http.ResponseWriter) bool {
	if s.clientService == nil {
		writeError(w, "client store unavailable", http.StatusServiceUnavailable)
		return false
	}
	return true
}

// --- request/response DTOs ---

type v1CreateClientRequest struct {
	Name             string  `json:"name"`
	Email            *string `json:"email"`
	Enabled          *bool   `json:"enabled"`
	GroupID          *string `json:"groupId"`
	QuotaBytes       *int64  `json:"quotaBytes"`
	QuotaResetPolicy string  `json:"quotaResetPolicy"`
	QuotaResetAt     *int64  `json:"quotaResetAt"`
	ExpiresAt        *int64  `json:"expiresAt"`
	DeviceLimit      *int    `json:"deviceLimit"`
	Notes            string  `json:"notes"`
	// Bind the client to inbounds at creation time. For each entry a credential
	// may be provided; otherwise one is generated by the caller-side flow.
	Bindings []v1BindingRequest `json:"bindings"`
}

type v1BindingRequest struct {
	InboundID  string `json:"inboundId"`
	Credential string `json:"credential"`
	Enabled    *bool  `json:"enabled"`
}

type v1UpdateClientRequest struct {
	Version          int     `json:"version"` // optimistic locking: must match current
	Name             string  `json:"name"`
	Email            *string `json:"email"`
	Enabled          *bool   `json:"enabled"`
	GroupID          *string `json:"groupId"`
	QuotaBytes       *int64  `json:"quotaBytes"`
	QuotaResetPolicy string  `json:"quotaResetPolicy"`
	QuotaResetAt     *int64  `json:"quotaResetAt"`
	ExpiresAt        *int64  `json:"expiresAt"`
	DeviceLimit      *int    `json:"deviceLimit"`
	Notes            string  `json:"notes"`
}

func (s *managementState) handleV1Clients(w http.ResponseWriter, r *http.Request) {
	if !s.clientsV1Enabled(w) {
		return
	}
	switch r.Method {
	case http.MethodGet:
		s.handleV1ListClients(w, r)
	case http.MethodPost:
		s.handleV1CreateClient(w, r)
	default:
		methodNotAllowed(w, http.MethodGet, http.MethodPost)
	}
}

// --- Bulk operations ---

type v1BulkRequest struct {
	Action     string   `json:"action"` // enable|disable|delete|extend_expiry|set_quota|reset_traffic|attach_inbound|detach_inbound
	ClientIDs  []string `json:"clientIds"`
	Days       *int     `json:"days"`       // for extend_expiry
	QuotaBytes *int64   `json:"quotaBytes"` // for set_quota
	InboundID  string   `json:"inboundId"`  // for attach/detach_inbound
}

type v1BulkResult struct {
	ID      string `json:"id"`
	OK      bool   `json:"ok"`
	Message string `json:"message,omitempty"`
}

// handleV1Bulk applies one action to many clients transactionally per client,
// collecting per-client results. A single failing client does not abort the
// rest; the summary reports each outcome honestly.
func (s *managementState) handleV1Bulk(w http.ResponseWriter, r *http.Request) {
	if !s.clientsV1Enabled(w) {
		return
	}
	if r.Method != http.MethodPost {
		methodNotAllowed(w, http.MethodPost)
		return
	}
	var req v1BulkRequest
	if !decodeJSONRequest(w, r, &req) {
		return
	}
	if req.Action == "" || len(req.ClientIDs) == 0 {
		writeError(w, "action and clientIds are required", http.StatusBadRequest)
		return
	}
	results := make([]v1BulkResult, 0, len(req.ClientIDs))
	succeeded := 0
	skipped := 0
	for _, id := range req.ClientIDs {
		res := v1BulkResult{ID: id}
		ok, sk, err := s.applyBulkAction(id, req)
		switch {
		case err != nil:
			res.OK = false
			res.Message = err.Error()
		case sk:
			res.OK = false
			res.Message = "skipped"
			skipped++
		default:
			res.OK = ok
			succeeded++
		}
		results = append(results, res)
	}
	failed := len(req.ClientIDs) - succeeded - skipped
	s.logUserAction(r, "bulk_"+req.Action, "clients", succeeded == len(req.ClientIDs), "")
	// A bulk mutation changes desired state for many clients: run a single
	// apply and return the honest revision/applyJob envelope.
	outcome := s.applyAfterClientMutation(r, actorFromRequest(r))
	resp := map[string]any{
		"action":    req.Action,
		"total":     len(req.ClientIDs),
		"succeeded": succeeded,
		"skipped":   skipped,
		"failed":    failed,
		"results":   results,
	}
	s.mergeOutcomeInto(resp, outcome)
	writeJSON(w, resp)
}

// applyBulkAction applies one bulk action to one client. It returns
// (applied, skipped, err): err for hard failures (not found, validation),
// skipped for no-op cases the plan calls skipped (already in desired state),
// applied=true when a change was persisted.
func (s *managementState) applyBulkAction(id string, req v1BulkRequest) (bool, bool, error) {
	existing, err := s.clientService.Get(id)
	if err != nil {
		return false, false, err
	}
	c := existing.Client
	switch req.Action {
	case "enable":
		c.Enabled = true
	case "disable":
		c.Enabled = false
	case "delete":
		return true, false, s.clientService.Delete(id)
	case "reset_quota":
		// Deprecated alias of reset_traffic kept for backward compatibility.
		fallthrough
	case "reset_traffic":
		// Clear actual recorded usage and the depleted flag. This is the
		// honest "reset traffic" (not merely un-depleting the client).
		if s.trafficStore != nil {
			if err := s.trafficStore.ResetForClient(id); err != nil {
				return false, false, err
			}
		}
		c.Depleted = false
		c.QuotaResetAt = nil
	case "set_quota":
		if req.QuotaBytes == nil || *req.QuotaBytes < 0 {
			return false, false, client.ErrValidation
		}
		c.QuotaBytes = req.QuotaBytes
	case "extend", "extend_expiry":
		if req.Days == nil || *req.Days <= 0 {
			return false, false, client.ErrValidation
		}
		var base int64
		now := nowUnixAPI()
		if c.ExpiresAt != nil && *c.ExpiresAt > now {
			base = *c.ExpiresAt
		} else {
			base = now
		}
		newExp := base + int64(*req.Days)*86400
		c.ExpiresAt = &newExp
	case "attach_inbound":
		if req.InboundID == "" {
			return false, false, client.ErrValidation
		}
		if _, err := s.clientService.AddBinding(id, req.InboundID); err != nil {
			return false, false, err
		}
		return true, false, nil
	case "detach_inbound":
		if req.InboundID == "" {
			return false, false, client.ErrValidation
		}
		// find binding id for this inbound
		bv := existing.Bindings
		for _, b := range bv {
			if b.InboundID == req.InboundID {
				return true, false, s.clientService.RemoveBinding(b.ID, id)
			}
		}
		return false, true, nil // not attached -> skipped
	default:
		return false, false, client.ErrValidation
	}
	_, err = s.clientService.Update(c, c.Version)
	return err == nil, false, err
}

// handleV1MigrateLegacy converts legacy inbound-embedded client profiles into
// the normalized Client+Binding+Credential model. It is idempotent (stable
// derived client IDs) so it is safe to re-run during a rolling migration. After
// migrating, the operator can drop the embedded profiles; normalized clients
// are rendered into live configs regardless.
func (s *managementState) handleV1MigrateLegacy(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		methodNotAllowed(w, http.MethodPost)
		return
	}
	if s.clientMigrator == nil {
		writeError(w, "client migration unavailable", http.StatusServiceUnavailable)
		return
	}
	s.mu.Lock()
	inbounds := append([]Inbound(nil), s.inbounds...)
	s.mu.Unlock()

	type inboundResult struct {
		Inbound            string `json:"inbound"`
		ClientsCreated     int    `json:"clientsCreated"`
		BindingsCreated    int    `json:"bindingsCreated"`
		CredentialsCreated int    `json:"credentialsCreated"`
		Skipped            int    `json:"skipped"`
	}
	results := []inboundResult{}
	totalCreated := 0
	for _, in := range inbounds {
		if len(in.Profiles) == 0 {
			continue
		}
		profiles := make([]client.LegacyProfile, 0, len(in.Profiles))
		for _, p := range in.Profiles {
			profiles = append(profiles, client.LegacyProfile{
				Name: p.Name, Username: p.Username, Password: p.Password, Enabled: p.Enabled,
			})
		}
		res, err := s.clientMigrator.MigrateInboundProfiles(in.Name, in.Protocol, profiles)
		if err != nil {
			s.logUserAction(r, "migrate_legacy", in.Name, false, err.Error())
			writeError(w, "migrate inbound "+in.Name+": "+err.Error(), http.StatusInternalServerError)
			return
		}
		totalCreated += res.ClientsCreated
		results = append(results, inboundResult{
			Inbound:            in.Name,
			ClientsCreated:     res.ClientsCreated,
			BindingsCreated:    res.BindingsCreated,
			CredentialsCreated: res.CredentialsCreated,
			Skipped:            res.Skipped,
		})
	}
	s.logUserAction(r, "migrate_legacy", "", true, "")
	outcome := s.applyAfterClientMutation(r, actorFromRequest(r))
	s.writeMutationResponse(w, http.StatusOK, map[string]any{
		"results":        results,
		"clientsCreated": totalCreated,
	}, outcome)
}

func nowUnixAPI() int64 { return time.Now().Unix() }

// applyAfterClientMutation bumps the desired revision and runs the apply job
// for a committed client mutation, returning the outcome so the handler can
// surface an honest mutation envelope. The client store is separate from the
// management state file, so the management mutation hooks are not triggered;
// we record the revision explicitly. Caller must not hold s.mu.
func (s *managementState) applyAfterClientMutation(r *http.Request, actor string) autoApplyOutcome {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.bumpDesiredRevisionLocked()
	return s.autoApplyResultLocked(r, actor)
}

// actorFromRequest extracts the authenticated username for audit/apply actor.
func actorFromRequest(r *http.Request) string {
	actor, _ := r.Context().Value(contextKeyUsername).(string)
	return actor
}

func (s *managementState) handleV1ListClients(w http.ResponseWriter, r *http.Request) {
	q := r.URL.Query()
	f := client.ListFilter{
		Page:       atoiDefault(q.Get("page"), 1),
		PageSize:   atoiDefault(q.Get("pageSize"), 25),
		Search:     q.Get("search"),
		Status:     q.Get("status"),
		InboundID:  q.Get("inboundId"),
		GroupID:    q.Get("groupId"),
		QuotaState: q.Get("quotaState"),
		Sort:       q.Get("sort"),
	}
	if v := q.Get("expiresBefore"); v != "" {
		if ts, err := strconv.ParseInt(v, 10, 64); err == nil {
			f.ExpiresBefore = &ts
		}
	}
	if v := q.Get("expiresAfter"); v != "" {
		if ts, err := strconv.ParseInt(v, 10, 64); err == nil {
			f.ExpiresAfter = &ts
		}
	}
	items, total, err := s.clientService.List(f)
	if err != nil {
		writeError(w, err.Error(), http.StatusInternalServerError)
		return
	}
	writeJSON(w, map[string]any{"items": items, "total": total, "page": f.Page, "pageSize": f.PageSize})
}

func (s *managementState) handleV1CreateClient(w http.ResponseWriter, r *http.Request) {
	var req v1CreateClientRequest
	if !decodeJSONRequest(w, r, &req) {
		return
	}
	enabled := true
	if req.Enabled != nil {
		enabled = *req.Enabled
	}
	c := client.Client{
		Name:             req.Name,
		Email:            req.Email,
		Enabled:          enabled,
		GroupID:          req.GroupID,
		QuotaBytes:       req.QuotaBytes,
		QuotaResetPolicy: req.QuotaResetPolicy,
		QuotaResetAt:     req.QuotaResetAt,
		ExpiresAt:        req.ExpiresAt,
		DeviceLimit:      req.DeviceLimit,
		Notes:            req.Notes,
	}
	// A4/A5: single SQL transaction. Client + bindings + credentials commit or
	// roll back atomically; exactly one apply runs for the fully-configured
	// client; no compensating deletes. A failure returns an error, never a 201
	// for a partially-created client.
	bindings := make([]client.BindingInput, 0, len(req.Bindings))
	for _, b := range req.Bindings {
		if b.InboundID == "" {
			continue
		}
		bindings = append(bindings, client.BindingInput{InboundID: b.InboundID, Credential: b.Credential})
	}
	final, err := s.clientService.CreateWithBindings(c, bindings)
	if err != nil {
		s.logUserAction(r, "create_client", req.Name, false, err.Error())
		s.writeV1ClientError(w, err)
		return
	}
	s.logUserAction(r, "create_client", req.Name, true, "")
	// A4: CreateWithBindings already triggered exactly one apply via the
	// notifier (after the transaction committed). Do NOT run a second apply
	// here — that would be the forbidden double-apply architecture.
	s.writeMutationResponse(w, http.StatusCreated, final, autoApplyOutcome{})
}

func (s *managementState) handleV1ClientByID(w http.ResponseWriter, r *http.Request) {
	if !s.clientsV1Enabled(w) {
		return
	}
	rest := strings.TrimPrefix(r.URL.Path, "/api/v1/clients/")
	parts := strings.Split(rest, "/")
	id := parts[0]
	if id == "" {
		writeNotFound(w)
		return
	}
	// Sub-resources: /api/v1/clients/{id}/bindings, /credentials, /subscription...
	if len(parts) > 1 {
		s.handleV1ClientSubresource(w, r, id, parts[1:])
		return
	}
	switch r.Method {
	case http.MethodGet:
		view, err := s.clientService.Get(id)
		if err != nil {
			writeNotFound(w)
			return
		}
		writeJSON(w, view)
	case http.MethodPut:
		s.handleV1UpdateClient(w, r, id)
	case http.MethodDelete:
		if err := s.clientService.Delete(id); err != nil {
			s.writeV1ClientError(w, err)
			return
		}
		s.logUserAction(r, "delete_client", id, true, "")
		outcome := s.applyAfterClientMutation(r, actorFromRequest(r))
		s.writeMutationResponse(w, http.StatusOK, map[string]string{"id": id}, outcome)
	default:
		methodNotAllowed(w, http.MethodGet, http.MethodPut, http.MethodDelete)
	}
}

func (s *managementState) handleV1UpdateClient(w http.ResponseWriter, r *http.Request, id string) {
	var req v1UpdateClientRequest
	if !decodeJSONRequest(w, r, &req) {
		return
	}
	existing, err := s.clientService.Get(id)
	if err != nil {
		writeNotFound(w)
		return
	}
	enabled := existing.Enabled
	if req.Enabled != nil {
		enabled = *req.Enabled
	}
	c := client.Client{
		ID:               id,
		Name:             req.Name,
		Email:            req.Email,
		Enabled:          enabled,
		GroupID:          req.GroupID,
		QuotaBytes:       req.QuotaBytes,
		QuotaResetPolicy: req.QuotaResetPolicy,
		QuotaResetAt:     req.QuotaResetAt,
		ExpiresAt:        req.ExpiresAt,
		DeviceLimit:      req.DeviceLimit,
		Notes:            req.Notes,
	}
	updated, err := s.clientService.Update(c, req.Version)
	if err != nil {
		s.logUserAction(r, "update_client", id, false, err.Error())
		s.writeV1ClientError(w, err)
		return
	}
	s.logUserAction(r, "update_client", id, true, "")
	outcome := s.applyAfterClientMutation(r, actorFromRequest(r))
	s.writeMutationResponse(w, http.StatusOK, updated, outcome)
}

func (s *managementState) handleV1ClientSubresource(w http.ResponseWriter, r *http.Request, clientID string, parts []string) {
	switch parts[0] {
	case "bindings":
		s.handleV1ClientBindings(w, r, clientID, parts)
	case "credentials":
		s.handleV1ClientCredentials(w, r, clientID, parts)
	case "tokens":
		if len(parts) == 1 {
			s.handleV1ClientTokens(w, r, clientID)
			return
		}
		// /tokens/{tokenId} or /tokens/{tokenId}/rotate
		tokenID := parts[1]
		action := ""
		if len(parts) > 2 {
			action = parts[2]
		}
		s.handleV1ClientTokenByID(w, r, clientID, tokenID, action)
	default:
		writeNotFound(w)
	}
}

func (s *managementState) handleV1ClientBindings(w http.ResponseWriter, r *http.Request, clientID string, parts []string) {
	if len(parts) == 1 { // /bindings
		if r.Method == http.MethodPost {
			var req v1BindingRequest
			if !decodeJSONRequest(w, r, &req) {
				return
			}
			b, err := s.clientService.AddBinding(clientID, req.InboundID)
			if err != nil {
				s.writeV1ClientError(w, err)
				return
			}
			if req.Credential != "" {
				_, _ = s.clientService.SetCredential(b.ID, "password", req.Credential)
			}
			s.logUserAction(r, "add_binding", clientID, true, req.InboundID)
			outcome := s.applyAfterClientMutation(r, actorFromRequest(r))
			s.writeMutationResponse(w, http.StatusCreated, b, outcome)
			return
		}
		methodNotAllowed(w, http.MethodPost)
		return
	}
	// /bindings/{bindingId}
	bindingID := parts[1]
	if r.Method == http.MethodPatch {
		var req struct {
			Enabled *bool `json:"enabled"`
			Version int   `json:"version"`
		}
		if !decodeJSONRequest(w, r, &req) {
			return
		}
		if req.Enabled == nil {
			writeError(w, "enabled is required", http.StatusBadRequest)
			return
		}
		b, err := s.clientService.SetBindingEnabled(bindingID, *req.Enabled, req.Version)
		if err != nil {
			s.writeV1ClientError(w, err)
			return
		}
		s.logUserAction(r, "update_binding", clientID, true, bindingID)
		outcome := s.applyAfterClientMutation(r, actorFromRequest(r))
		s.writeMutationResponse(w, http.StatusOK, b, outcome)
		return
	}
	if r.Method == http.MethodDelete {
		if err := s.clientService.RemoveBinding(bindingID, clientID); err != nil {
			s.writeV1ClientError(w, err)
			return
		}
		s.logUserAction(r, "remove_binding", clientID, true, bindingID)
		outcome := s.applyAfterClientMutation(r, actorFromRequest(r))
		s.writeMutationResponse(w, http.StatusOK, map[string]string{"id": bindingID}, outcome)
		return
	}
	methodNotAllowed(w, http.MethodPatch, http.MethodDelete)
}

func (s *managementState) handleV1ClientCredentials(w http.ResponseWriter, r *http.Request, clientID string, parts []string) {
	// /credentials/{bindingId} with POST {kind,value} to set; POST .../rotate to rotate.
	if len(parts) < 2 {
		writeNotFound(w)
		return
	}
	bindingID := parts[1]
	if r.Method == http.MethodPost && len(parts) == 2 {
		var req struct {
			Kind  string `json:"kind"`
			Value string `json:"value"`
		}
		if !decodeJSONRequest(w, r, &req) {
			return
		}
		if req.Kind == "" {
			req.Kind = "password"
		}
		cred, err := s.clientService.SetCredential(bindingID, req.Kind, req.Value)
		if err != nil {
			s.writeV1ClientError(w, err)
			return
		}
		s.logUserAction(r, "set_credential", clientID, true, bindingID)
		outcome := s.applyAfterClientMutation(r, actorFromRequest(r))
		s.writeMutationResponse(w, http.StatusCreated, cred, outcome)
		return
	}
	if r.Method == http.MethodPost && len(parts) == 3 && parts[2] == "rotate" {
		var req struct {
			Kind  string `json:"kind"`
			Value string `json:"value"`
		}
		if !decodeJSONRequest(w, r, &req) {
			return
		}
		if req.Kind == "" {
			req.Kind = "password"
		}
		// Server-generated rotate (preferred, capability-driven): when no value
		// is supplied the server generates a high-entropy secret and returns it
		// exactly once. An explicit value keeps the legacy caller-supplied path.
		if req.Value == "" {
			gen, err := s.clientService.RotateCredentialGenerated(bindingID, req.Kind)
			if err != nil {
				s.writeV1ClientError(w, err)
				return
			}
			s.logUserAction(r, "rotate_credential", clientID, true, bindingID)
			outcome := s.applyAfterClientMutation(r, actorFromRequest(r))
			s.writeMutationResponse(w, http.StatusOK, gen, outcome)
			return
		}
		cred, err := s.clientService.RotateCredential(bindingID, req.Kind, req.Value)
		if err != nil {
			s.writeV1ClientError(w, err)
			return
		}
		s.logUserAction(r, "rotate_credential", clientID, true, bindingID)
		outcome := s.applyAfterClientMutation(r, actorFromRequest(r))
		s.writeMutationResponse(w, http.StatusOK, cred, outcome)
		return
	}
	writeNotFound(w)
}

// writeV1ClientError maps domain errors to HTTP status codes honestly.
func (s *managementState) writeV1ClientError(w http.ResponseWriter, err error) {
	switch {
	case errors.Is(err, client.ErrNotFound):
		writeError(w, err.Error(), http.StatusNotFound)
	case errors.Is(err, client.ErrVersionConflict):
		writeError(w, err.Error(), http.StatusConflict)
	case errors.Is(err, client.ErrDuplicateBinding):
		writeError(w, err.Error(), http.StatusConflict)
	case errors.Is(err, client.ErrValidation):
		writeError(w, err.Error(), http.StatusBadRequest)
	default:
		writeError(w, err.Error(), http.StatusInternalServerError)
	}
}

func atoiDefault(s string, def int) int {
	if s == "" {
		return def
	}
	n, err := strconv.Atoi(s)
	if err != nil || n < 1 {
		return def
	}
	return n
}

var _ = json.Marshal
