package api

import (
	"encoding/json"
	"errors"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/mikkelchokolate/Veil/internal/client"
)

// registerClientV1Routes registers the normalized client management endpoints
// (Stage 1). These operate on the Client domain model, never on
// inbound-embedded profiles.
func (s *managementState) registerClientV1Routes(mux *http.ServeMux) {
	mux.HandleFunc("/api/v1/clients", s.handleV1Clients)
	mux.HandleFunc("/api/v1/clients/bulk", s.handleV1Bulk)
	mux.HandleFunc("/api/v1/clients/", s.handleV1ClientByID)
}

// clientsV1Enabled reports whether the normalized store is available.
func (s *managementState) clientsV1Enabled(w http.ResponseWriter) bool {
	if s.clientService == nil {
		writeError(w, "client store unavailable", http.StatusServiceUnavailable)
		return false
	}
	return true
}

// --- request/response DTOs ---

type v1CreateClientRequest struct {
	Name             string  `json:"name"`
	Email            *string `json:"email"`
	Enabled          *bool   `json:"enabled"`
	GroupID          *string `json:"groupId"`
	QuotaBytes       *int64  `json:"quotaBytes"`
	QuotaResetPolicy string  `json:"quotaResetPolicy"`
	QuotaResetAt     *int64  `json:"quotaResetAt"`
	ExpiresAt        *int64  `json:"expiresAt"`
	DeviceLimit      *int    `json:"deviceLimit"`
	Notes            string  `json:"notes"`
	// Bind the client to inbounds at creation time. For each entry a credential
	// may be provided; otherwise one is generated by the caller-side flow.
	Bindings []v1BindingRequest `json:"bindings"`
}

type v1BindingRequest struct {
	InboundID  string `json:"inboundId"`
	Credential string `json:"credential"`
	Enabled    *bool  `json:"enabled"`
}

type v1UpdateClientRequest struct {
	Version          int     `json:"version"` // optimistic locking: must match current
	Name             string  `json:"name"`
	Email            *string `json:"email"`
	Enabled          *bool   `json:"enabled"`
	GroupID          *string `json:"groupId"`
	QuotaBytes       *int64  `json:"quotaBytes"`
	QuotaResetPolicy string  `json:"quotaResetPolicy"`
	QuotaResetAt     *int64  `json:"quotaResetAt"`
	ExpiresAt        *int64  `json:"expiresAt"`
	DeviceLimit      *int    `json:"deviceLimit"`
	Notes            string  `json:"notes"`
}

func (s *managementState) handleV1Clients(w http.ResponseWriter, r *http.Request) {
	if !s.clientsV1Enabled(w) {
		return
	}
	switch r.Method {
	case http.MethodGet:
		s.handleV1ListClients(w, r)
	case http.MethodPost:
		s.handleV1CreateClient(w, r)
	default:
		methodNotAllowed(w, http.MethodGet, http.MethodPost)
	}
}

// --- Bulk operations ---

type v1BulkRequest struct {
	Action    string   `json:"action"` // enable | disable | delete | extend | reset_quota
	ClientIDs []string `json:"clientIds"`
	Days      *int     `json:"days"` // for extend
}

type v1BulkResult struct {
	ID      string `json:"id"`
	OK      bool   `json:"ok"`
	Message string `json:"message,omitempty"`
}

// handleV1Bulk applies one action to many clients transactionally per client,
// collecting per-client results. A single failing client does not abort the
// rest; the summary reports each outcome honestly.
func (s *managementState) handleV1Bulk(w http.ResponseWriter, r *http.Request) {
	if !s.clientsV1Enabled(w) {
		return
	}
	if r.Method != http.MethodPost {
		methodNotAllowed(w, http.MethodPost)
		return
	}
	var req v1BulkRequest
	if !decodeJSONRequest(w, r, &req) {
		return
	}
	if req.Action == "" || len(req.ClientIDs) == 0 {
		writeError(w, "action and clientIds are required", http.StatusBadRequest)
		return
	}
	results := make([]v1BulkResult, 0, len(req.ClientIDs))
	succeeded := 0
	for _, id := range req.ClientIDs {
		res := v1BulkResult{ID: id}
		err := s.applyBulkAction(id, req)
		if err != nil {
			res.OK = false
			res.Message = err.Error()
		} else {
			res.OK = true
			succeeded++
		}
		results = append(results, res)
	}
	s.logUserAction(r, "bulk_"+req.Action, "clients", succeeded == len(req.ClientIDs), "")
	writeJSON(w, map[string]any{
		"action":    req.Action,
		"total":     len(req.ClientIDs),
		"succeeded": succeeded,
		"failed":    len(req.ClientIDs) - succeeded,
		"results":   results,
	})
}

func (s *managementState) applyBulkAction(id string, req v1BulkRequest) error {
	existing, err := s.clientService.Get(id)
	if err != nil {
		return err
	}
	c := existing.Client
	switch req.Action {
	case "enable":
		c.Enabled = true
	case "disable":
		c.Enabled = false
	case "delete":
		return s.clientService.Delete(id)
	case "reset_quota":
		c.Depleted = false
		c.QuotaResetAt = nil
	case "extend":
		if req.Days == nil || *req.Days <= 0 {
			return client.ErrValidation
		}
		var base int64
		now := nowUnixAPI()
		if c.ExpiresAt != nil && *c.ExpiresAt > now {
			base = *c.ExpiresAt
		} else {
			base = now
		}
		newExp := base + int64(*req.Days)*86400
		c.ExpiresAt = &newExp
	default:
		return client.ErrValidation
	}
	_, err = s.clientService.Update(c, c.Version)
	return err
}

func nowUnixAPI() int64 { return time.Now().Unix() }

func (s *managementState) handleV1ListClients(w http.ResponseWriter, r *http.Request) {
	q := r.URL.Query()
	f := client.ListFilter{
		Page:       atoiDefault(q.Get("page"), 1),
		PageSize:   atoiDefault(q.Get("pageSize"), 25),
		Search:     q.Get("search"),
		Status:     q.Get("status"),
		InboundID:  q.Get("inboundId"),
		GroupID:    q.Get("groupId"),
		QuotaState: q.Get("quotaState"),
		Sort:       q.Get("sort"),
	}
	if v := q.Get("expiresBefore"); v != "" {
		if ts, err := strconv.ParseInt(v, 10, 64); err == nil {
			f.ExpiresBefore = &ts
		}
	}
	if v := q.Get("expiresAfter"); v != "" {
		if ts, err := strconv.ParseInt(v, 10, 64); err == nil {
			f.ExpiresAfter = &ts
		}
	}
	items, total, err := s.clientService.List(f)
	if err != nil {
		writeError(w, err.Error(), http.StatusInternalServerError)
		return
	}
	writeJSON(w, map[string]any{"items": items, "total": total, "page": f.Page, "pageSize": f.PageSize})
}

func (s *managementState) handleV1CreateClient(w http.ResponseWriter, r *http.Request) {
	var req v1CreateClientRequest
	if !decodeJSONRequest(w, r, &req) {
		return
	}
	enabled := true
	if req.Enabled != nil {
		enabled = *req.Enabled
	}
	c := client.Client{
		Name:             req.Name,
		Email:            req.Email,
		Enabled:          enabled,
		GroupID:          req.GroupID,
		QuotaBytes:       req.QuotaBytes,
		QuotaResetPolicy: req.QuotaResetPolicy,
		QuotaResetAt:     req.QuotaResetAt,
		ExpiresAt:        req.ExpiresAt,
		DeviceLimit:      req.DeviceLimit,
		Notes:            req.Notes,
	}
	created, err := s.clientService.Create(c)
	if err != nil {
		s.writeV1ClientError(w, err)
		return
	}
	// Create bindings (+ credentials) transactionally after the client.
	for _, b := range req.Bindings {
		if b.InboundID == "" {
			continue
		}
		bind, berr := s.clientService.AddBinding(created.ID, b.InboundID)
		if berr != nil {
			s.logUserAction(r, "create_client", req.Name, false, "bind: "+berr.Error())
			continue
		}
		if b.Credential != "" {
			if _, cerr := s.clientService.SetCredential(bind.ID, "password", b.Credential); cerr != nil {
				s.logUserAction(r, "create_client", req.Name, false, "credential: "+cerr.Error())
			}
		}
	}
	s.logUserAction(r, "create_client", req.Name, true, "")
	final, _ := s.clientService.Get(created.ID)
	writeJSONStatus(w, http.StatusCreated, final)
}

func (s *managementState) handleV1ClientByID(w http.ResponseWriter, r *http.Request) {
	if !s.clientsV1Enabled(w) {
		return
	}
	rest := strings.TrimPrefix(r.URL.Path, "/api/v1/clients/")
	parts := strings.Split(rest, "/")
	id := parts[0]
	if id == "" {
		writeNotFound(w)
		return
	}
	// Sub-resources: /api/v1/clients/{id}/bindings, /credentials, /subscription...
	if len(parts) > 1 {
		s.handleV1ClientSubresource(w, r, id, parts[1:])
		return
	}
	switch r.Method {
	case http.MethodGet:
		view, err := s.clientService.Get(id)
		if err != nil {
			writeNotFound(w)
			return
		}
		writeJSON(w, view)
	case http.MethodPut:
		s.handleV1UpdateClient(w, r, id)
	case http.MethodDelete:
		if err := s.clientService.Delete(id); err != nil {
			s.writeV1ClientError(w, err)
			return
		}
		s.logUserAction(r, "delete_client", id, true, "")
		writeJSON(w, map[string]string{"id": id})
	default:
		methodNotAllowed(w, http.MethodGet, http.MethodPut, http.MethodDelete)
	}
}

func (s *managementState) handleV1UpdateClient(w http.ResponseWriter, r *http.Request, id string) {
	var req v1UpdateClientRequest
	if !decodeJSONRequest(w, r, &req) {
		return
	}
	existing, err := s.clientService.Get(id)
	if err != nil {
		writeNotFound(w)
		return
	}
	enabled := existing.Enabled
	if req.Enabled != nil {
		enabled = *req.Enabled
	}
	c := client.Client{
		ID:               id,
		Name:             req.Name,
		Email:            req.Email,
		Enabled:          enabled,
		GroupID:          req.GroupID,
		QuotaBytes:       req.QuotaBytes,
		QuotaResetPolicy: req.QuotaResetPolicy,
		QuotaResetAt:     req.QuotaResetAt,
		ExpiresAt:        req.ExpiresAt,
		DeviceLimit:      req.DeviceLimit,
		Notes:            req.Notes,
	}
	updated, err := s.clientService.Update(c, req.Version)
	if err != nil {
		s.logUserAction(r, "update_client", id, false, err.Error())
		s.writeV1ClientError(w, err)
		return
	}
	s.logUserAction(r, "update_client", id, true, "")
	writeJSON(w, updated)
}

func (s *managementState) handleV1ClientSubresource(w http.ResponseWriter, r *http.Request, clientID string, parts []string) {
	switch parts[0] {
	case "bindings":
		s.handleV1ClientBindings(w, r, clientID, parts)
	case "credentials":
		s.handleV1ClientCredentials(w, r, clientID, parts)
	case "tokens":
		if len(parts) == 1 {
			s.handleV1ClientTokens(w, r, clientID)
			return
		}
		// /tokens/{tokenId} or /tokens/{tokenId}/rotate
		tokenID := parts[1]
		action := ""
		if len(parts) > 2 {
			action = parts[2]
		}
		s.handleV1ClientTokenByID(w, r, clientID, tokenID, action)
	default:
		writeNotFound(w)
	}
}

func (s *managementState) handleV1ClientBindings(w http.ResponseWriter, r *http.Request, clientID string, parts []string) {
	if len(parts) == 1 { // /bindings
		if r.Method == http.MethodPost {
			var req v1BindingRequest
			if !decodeJSONRequest(w, r, &req) {
				return
			}
			b, err := s.clientService.AddBinding(clientID, req.InboundID)
			if err != nil {
				s.writeV1ClientError(w, err)
				return
			}
			if req.Credential != "" {
				_, _ = s.clientService.SetCredential(b.ID, "password", req.Credential)
			}
			s.logUserAction(r, "add_binding", clientID, true, req.InboundID)
			writeJSONStatus(w, http.StatusCreated, b)
			return
		}
		methodNotAllowed(w, http.MethodPost)
		return
	}
	// /bindings/{bindingId}
	bindingID := parts[1]
	if r.Method == http.MethodDelete {
		if err := s.clientService.RemoveBinding(bindingID, clientID); err != nil {
			s.writeV1ClientError(w, err)
			return
		}
		s.logUserAction(r, "remove_binding", clientID, true, bindingID)
		writeJSON(w, map[string]string{"id": bindingID})
		return
	}
	methodNotAllowed(w, http.MethodDelete)
}

func (s *managementState) handleV1ClientCredentials(w http.ResponseWriter, r *http.Request, clientID string, parts []string) {
	// /credentials/{bindingId} with POST {kind,value} to set; POST .../rotate to rotate.
	if len(parts) < 2 {
		writeNotFound(w)
		return
	}
	bindingID := parts[1]
	if r.Method == http.MethodPost && len(parts) == 2 {
		var req struct {
			Kind  string `json:"kind"`
			Value string `json:"value"`
		}
		if !decodeJSONRequest(w, r, &req) {
			return
		}
		if req.Kind == "" {
			req.Kind = "password"
		}
		cred, err := s.clientService.SetCredential(bindingID, req.Kind, req.Value)
		if err != nil {
			s.writeV1ClientError(w, err)
			return
		}
		s.logUserAction(r, "set_credential", clientID, true, bindingID)
		writeJSONStatus(w, http.StatusCreated, cred)
		return
	}
	if r.Method == http.MethodPost && len(parts) == 3 && parts[2] == "rotate" {
		var req struct {
			Kind  string `json:"kind"`
			Value string `json:"value"`
		}
		if !decodeJSONRequest(w, r, &req) {
			return
		}
		if req.Kind == "" {
			req.Kind = "password"
		}
		cred, err := s.clientService.RotateCredential(bindingID, req.Kind, req.Value)
		if err != nil {
			s.writeV1ClientError(w, err)
			return
		}
		s.logUserAction(r, "rotate_credential", clientID, true, bindingID)
		writeJSON(w, cred)
		return
	}
	writeNotFound(w)
}

// writeV1ClientError maps domain errors to HTTP status codes honestly.
func (s *managementState) writeV1ClientError(w http.ResponseWriter, err error) {
	switch {
	case errors.Is(err, client.ErrNotFound):
		writeError(w, err.Error(), http.StatusNotFound)
	case errors.Is(err, client.ErrVersionConflict):
		writeError(w, err.Error(), http.StatusConflict)
	case errors.Is(err, client.ErrDuplicateBinding):
		writeError(w, err.Error(), http.StatusConflict)
	case errors.Is(err, client.ErrValidation):
		writeError(w, err.Error(), http.StatusBadRequest)
	default:
		writeError(w, err.Error(), http.StatusInternalServerError)
	}
}

func atoiDefault(s string, def int) int {
	if s == "" {
		return def
	}
	n, err := strconv.Atoi(s)
	if err != nil || n < 1 {
		return def
	}
	return n
}

var _ = json.Marshal
