package panel

func init() {
	installTranslationCatalog(LocaleEnglish, map[string]string{
		"common.actions":               "Actions",
		"common.current":               "Current",
		"common.expires":               "Expires",
		"common.yes":                   "yes",
		"common.no":                    "no",
		"status.notLoaded":             "Not loaded",
		"status.noUsers":               "No users registered",
		"status.noSessions":            "No active sessions",
		"status.loadingUsers":          "Loading users...",
		"status.loadingSessions":       "Loading sessions...",
		"status.accessDenied":          "Access Denied (Admin role required)",
		"status.requestFailed":         "Request failed: {error}",
		"status.loadFailed":            "Load failed: {error}",
		"status.copyFailed":            "Copy failed: {error}",
		"status.downloadFailed":        "Download failed: {error}",
		"status.restoreCancelled":      "Restore cancelled",
		"status.restoreTimedOut":       "Restore job polling timed out",
		"placeholder.domain":           "vpn.example.com",
		"placeholder.hostname":         "example.com",
		"placeholder.ipAddress":        "8.8.8.8",
		"placeholder.userPassword":     "Password",
		"placeholder.keepPassword":     "Leave blank to keep current",
		"users.managementTitle":        "User Management",
		"users.managementSummary":      "Manage administrative and viewer credentials. Viewer accounts can view diagnostics, settings, and stats, but cannot add/delete inbounds, modify routing rules, or apply changes.",
		"users.activeSessions":         "Active Sessions",
		"users.sessionsSummary":        "Review browser sessions and revoke stale operator access. The current session is marked so it is harder to lock yourself out accidentally.",
		"users.loadSessions":           "Load sessions",
		"users.apiTokenRotation":       "API Token Rotation",
		"users.apiTokenSummaryStart":   "Generate a replacement API token, update",
		"users.apiTokenSummaryEnd":     "in your service environment or restart command, then restart the Panel. Existing browser sessions are managed above.",
		"users.generateToken":          "Generate token",
		"users.copyToken":              "Copy generated token",
		"users.noGeneratedToken":       "No generated token",
		"users.statusOutput":           "Status Output",
		"users.revoke":                 "Revoke",
		"users.revokeSelf":             "Revoke self",
		"users.edit":                   "Edit",
		"backups.disasterRecovery":     "Disaster Recovery",
		"backups.summaryStart":         "Archives are encrypted with the server-side scheduled backup passphrase. Configure it once with",
		"backups.summaryEnd":           "; the browser never receives the passphrase.",
		"backups.daily":                "Daily copies",
		"backups.weekly":               "Weekly copies",
		"backups.monthly":              "Monthly copies",
		"backups.create":               "Create encrypted backup",
		"backups.applyRetention":       "Apply retention",
		"backups.created":              "Created",
		"backups.archive":              "Archive",
		"backups.size":                 "Size",
		"backups.encrypted":            "Encrypted",
		"backups.verify":               "Verify",
		"confirm.pruneBackups":         "Apply the displayed daily, weekly, and monthly retention policy? Deleted archives cannot be recovered from this host.",
		"confirm.restoreBackupPrompt":  "Restore overwrites live state and revokes existing sessions. Type the archive name to continue:\n{name}",
		"apply.planTitle":              "Apply plan",
		"apply.planSummary":            "Validate current management state and show staged config/reload actions before any real service changes:",
		"apply.healthSummary":          "Service reload also runs fixed health checks and automatically rolls live configs back if reload or health fails.",
		"apply.buildPlan":              "Build apply plan",
		"apply.stagedFiles":            "Apply staged files",
		"apply.liveConfigs":            "Apply live configs",
		"apply.reloadServices":         "Reload and health check services",
		"apply.safePreview":            "Safe apply preview",
		"apply.previewSummary":         "Shows file-level config changes, runtime actions, and DNS/TLS/firewall warnings without exposing generated config contents or secrets.",
		"apply.buildFirst":             "Safety warnings: build a plan first",
		"apply.operation":              "Operation",
		"apply.target":                 "Target",
		"apply.interruptionRisk":       "Interruption risk",
		"apply.rollback":               "Rollback",
		"apply.validatedBy":            "Validated by",
		"apply.previewEmpty":           "Build a plan to preview managed files and runtime actions.",
		"apply.historyStage":           "History stage",
		"apply.historySuccess":         "History success",
		"apply.historyLimit":           "History limit",
		"apply.loadHistory":            "Load apply history",
		"apply.runtimeNotPlanned":      "Runtime units: not planned",
		"apply.runtimeNone":            "Runtime units: none required",
		"apply.runtimeList":            "Runtime units: {runtimes}",
		"apply.warningSummary":         "Safety warnings: {warnings}",
		"apply.warningInvalid":         "Plan is invalid; fix validation errors before applying.",
		"apply.warningErrors":          "Plan errors are present in the raw output.",
		"apply.warningConnectionDrop":  "One or more service restarts can drop active proxy connections.",
		"apply.warningFirewall":        "Firewall changes can lock out remote access; verify SSH and provider console access before applying.",
		"apply.warningDNS":             "DNS changes depend on public records and propagation before client links work.",
		"apply.warningTLS":             "TLS changes require valid domain reachability and certificate issuance.",
		"apply.warningServiceRestart":  "Service reload or restart can interrupt active proxy sessions.",
		"apply.warningNone":            "No DNS/TLS/firewall/service warnings detected in plan metadata.",
		"diagnostics.logs":             "Service logs",
		"diagnostics.logsSummary":      "View recent journald logs for managed services.",
		"diagnostics.serviceUnit":      "Service unit",
		"diagnostics.lines":            "Lines",
		"diagnostics.loadLogs":         "Load logs",
		"diagnostics.dns":              "DNS lookup",
		"diagnostics.dnsSummary":       "Resolve a hostname from the server using",
		"diagnostics.hostname":         "Hostname",
		"diagnostics.lookup":           "Lookup hostname",
		"diagnostics.ping":             "Ping",
		"diagnostics.pingSummary":      "Ping a host from the server using",
		"diagnostics.host":             "Host",
		"diagnostics.firewall":         "Firewall",
		"diagnostics.firewallSummary":  "Check UFW firewall status and planned rules from",
		"diagnostics.loadFirewall":     "Load firewall",
		"diagnostics.speedtest":        "Speedtest",
		"diagnostics.speedtestSummary": "Run server-side speedtest-cli/Ookla speedtest from the panel.",
		"diagnostics.runSpeedtest":     "Run speedtest",
		"inbounds.title":               "Inbounds",
		"inbounds.summaryStart":        "Create, update, or delete",
		"inbounds.add":                 "Add Inbound",
		"inbounds.editTitle":           "Edit Inbound: {name}",
		"inbounds.nameRequired":        "Inbound name is required",
		"inbounds.validationPending":   "Validation runs as fields change.",
		"inbounds.validationChecking":  "Checking configuration...",
		"inbounds.validationReady":     "Configuration is ready to save.",
		"inbounds.name":                "Name",
		"inbounds.transport":           "Transport",
		"inbounds.clientProfiles":      "Client profiles (JSON)",
		"inbounds.profileHint":         "Use Add profile for multiple users on one Inbound, or edit JSON directly.",
		"confirm.deleteInbound":        "Delete inbound {name}?",
		"routing.title":                "Routing rules",
		"routing.summaryStart":         "List, create, update, or delete routing rules through",
		"routing.add":                  "Add Routing Rule",
		"routing.edit":                 "Edit Routing Rule",
		"routing.addRule":              "Add Rule",
		"routing.save":                 "Save routing rule",
		"routing.delete":               "Delete routing rule",
		"routing.nameRequired":         "Routing rule name is required",
		"routing.empty":                "Click 'Refresh' or load to display routing rules.",
		"routing.match":                "Match",
		"routing.outbound":             "Outbound",
		"routing.presets":              "Preset selectors",
		"routing.applyPreset":          "Apply routing preset",
		"routing.loadPresets":          "Load Presets API",
		"routing.loadRaw":              "Load Raw API Response",
		"confirm.deleteRoutingRule":    "Delete routing rule {name}?",
		"clientLinks.title":            "Client links",
		"clientLinks.generateCurrent":  "Generate current",
		"clientLinks.connectionTitle":  "Client Connection Links",
		"clientLinks.inboundTitle":     "Client Links: {name}",
		"clientLinks.showQR":           "Show QR",
		"clientLinks.renderingQR":      "Rendering QR...",
		"clientLinks.nothingToCopy":    "Nothing to copy yet",
		"clientLinks.copied":           "Copied!",
		"modal.addInbound":             "Add Inbound",
		"modal.closeSymbol":            "×",
		"settings.title":               "Settings",
		"settings.panelAccess":         "Panel access",
		"settings.panelListen":         "Panel listen",
		"settings.webBasePath":         "Web base path",
		"settings.mode":                "Mode",
		"settings.domain":              "Domain",
		"settings.email":               "Email",
		"settings.masqueradeURL":       "Masquerade URL",
		"settings.fallbackRoot":        "Fallback root",
		"settings.load":                "Load settings",
		"settings.save":                "Save settings",
		"runtime.systemResources":      "System resources",
		"runtime.refreshTelemetry":     "Refresh telemetry",
		"runtime.cpuUsage":             "CPU Usage",
		"runtime.memoryUsage":          "Memory Usage",
		"runtime.diskSpace":            "Disk Space",
		"runtime.networkInterfaces":    "Network interfaces",
		"runtime.loadNetwork":          "Load network stats",
		"runtime.managedProcesses":     "Managed processes",
		"runtime.loadProcesses":        "Load processes",
		"runtime.listeningPorts":       "Listening ports",
		"runtime.loadConnections":      "Load connections",
		"runtime.diskUsage":            "Disk usage",
		"runtime.loadDisk":             "Load disk usage",
		"service.status":               "Service status",
		"service.loadStatus":           "Load service status",
		"service.autoRefreshOff":       "Auto-refresh: OFF",
		"service.autoRefreshOn":        "Auto-refresh: ON (10s)",
		"warp.title":                   "WARP Integration Status",
		"warp.connectionSettings":      "Connection settings",
		"warp.credentials":             "Credentials",
		"warp.proxyRouting":            "Proxy & Routing",
		"warp.endpoint":                "Endpoint",
		"warp.privateKey":              "WireGuard private key",
		"warp.peerKey":                 "Peer public key",
		"warp.license":                 "Optional WARP+ license",
		"warp.localAddress":            "Local address",
		"warp.reserved":                "Reserved bytes",
		"warp.socksListen":             "SOCKS listen",
		"warp.socksPort":               "SOCKS port",
		"warp.load":                    "Load WARP",
		"warp.save":                    "Save WARP config",
	})

	installTranslationCatalog(LocaleRussian, map[string]string{
		"common.actions":               "Действия",
		"common.current":               "Текущая",
		"common.expires":               "Истекает",
		"common.yes":                   "да",
		"common.no":                    "нет",
		"status.notLoaded":             "Не загружено",
		"status.noUsers":               "Пользователей нет",
		"status.noSessions":            "Активных сессий нет",
		"status.loadingUsers":          "Загрузка пользователей...",
		"status.loadingSessions":       "Загрузка сессий...",
		"status.accessDenied":          "Доступ запрещён: требуется роль администратора",
		"status.requestFailed":         "Ошибка запроса: {error}",
		"status.loadFailed":            "Ошибка загрузки: {error}",
		"status.copyFailed":            "Ошибка копирования: {error}",
		"status.downloadFailed":        "Ошибка скачивания: {error}",
		"status.restoreCancelled":      "Восстановление отменено",
		"status.restoreTimedOut":       "Истекло время ожидания восстановления",
		"placeholder.domain":           "vpn.example.com",
		"placeholder.hostname":         "example.com",
		"placeholder.ipAddress":        "8.8.8.8",
		"placeholder.userPassword":     "Пароль",
		"placeholder.keepPassword":     "Оставьте пустым, чтобы сохранить текущий",
		"users.managementTitle":        "Управление пользователями",
		"users.managementSummary":      "Управляйте учётными данными администраторов и наблюдателей. Наблюдатели могут просматривать диагностику, настройки и статистику, но не могут менять подключения, маршруты или применять конфигурацию.",
		"users.activeSessions":         "Активные сессии",
		"users.sessionsSummary":        "Проверяйте сессии браузера и отзывайте устаревший доступ. Текущая сессия отмечена, чтобы снизить риск случайной блокировки.",
		"users.loadSessions":           "Загрузить сессии",
		"users.apiTokenRotation":       "Ротация API-токена",
		"users.apiTokenSummaryStart":   "Создайте новый API-токен, обновите",
		"users.apiTokenSummaryEnd":     "в окружении сервиса или команде запуска, затем перезапустите панель. Сессии браузера управляются выше.",
		"users.generateToken":          "Создать токен",
		"users.copyToken":              "Копировать созданный токен",
		"users.noGeneratedToken":       "Токен ещё не создан",
		"users.statusOutput":           "Состояние",
		"users.revoke":                 "Отозвать",
		"users.revokeSelf":             "Отозвать текущую",
		"users.edit":                   "Изменить",
		"backups.disasterRecovery":     "Аварийное восстановление",
		"backups.summaryStart":         "Архивы шифруются серверной парольной фразой плановых копий. Настройте её один раз командой",
		"backups.summaryEnd":           "; браузер никогда не получает парольную фразу.",
		"backups.daily":                "Дневные копии",
		"backups.weekly":               "Недельные копии",
		"backups.monthly":              "Месячные копии",
		"backups.create":               "Создать зашифрованную копию",
		"backups.applyRetention":       "Применить хранение",
		"backups.created":              "Создана",
		"backups.archive":              "Архив",
		"backups.size":                 "Размер",
		"backups.encrypted":            "Зашифрован",
		"backups.verify":               "Проверить",
		"confirm.pruneBackups":         "Применить показанную политику дневного, недельного и месячного хранения? Удалённые архивы нельзя восстановить с этого хоста.",
		"confirm.restoreBackupPrompt":  "Восстановление перезапишет рабочее состояние и отзовёт существующие сессии. Введите имя архива для продолжения:\n{name}",
		"apply.planTitle":              "План применения",
		"apply.planSummary":            "Проверьте текущее состояние и просмотрите действия с конфигурацией и сервисами до реальных изменений:",
		"apply.healthSummary":          "Перезагрузка сервисов включает фиксированные проверки здоровья и автоматически откатывает конфигурацию при ошибке.",
		"apply.buildPlan":              "Построить план",
		"apply.stagedFiles":            "Применить подготовленные файлы",
		"apply.liveConfigs":            "Применить рабочие конфигурации",
		"apply.reloadServices":         "Перезагрузить и проверить сервисы",
		"apply.safePreview":            "Безопасный предпросмотр",
		"apply.previewSummary":         "Показывает изменения файлов, действия сервисов и предупреждения DNS, TLS и firewall без раскрытия конфигураций и секретов.",
		"apply.buildFirst":             "Предупреждения безопасности: сначала постройте план",
		"apply.operation":              "Операция",
		"apply.target":                 "Цель",
		"apply.interruptionRisk":       "Риск прерывания",
		"apply.rollback":               "Откат",
		"apply.validatedBy":            "Проверено",
		"apply.previewEmpty":           "Постройте план для предпросмотра файлов и действий сервисов.",
		"apply.historyStage":           "Этап истории",
		"apply.historySuccess":         "Результат истории",
		"apply.historyLimit":           "Лимит истории",
		"apply.loadHistory":            "Загрузить историю",
		"apply.runtimeNotPlanned":      "Сервисы: план ещё не построен",
		"apply.runtimeNone":            "Сервисы: перезапуск не требуется",
		"apply.runtimeList":            "Сервисы: {runtimes}",
		"apply.warningSummary":         "Предупреждения безопасности: {warnings}",
		"apply.warningInvalid":         "План недействителен; исправьте ошибки проверки перед применением.",
		"apply.warningErrors":          "Исходный ответ содержит ошибки плана.",
		"apply.warningConnectionDrop":  "Перезапуск одного или нескольких сервисов может разорвать активные прокси-соединения.",
		"apply.warningFirewall":        "Изменения firewall могут заблокировать удалённый доступ; перед применением проверьте SSH и консоль провайдера.",
		"apply.warningDNS":             "Для работы клиентских ссылок изменения DNS требуют публичных записей и времени на распространение.",
		"apply.warningTLS":             "Для изменений TLS нужны доступный домен и успешный выпуск сертификата.",
		"apply.warningServiceRestart":  "Перезагрузка или перезапуск сервиса может прервать активные прокси-сессии.",
		"apply.warningNone":            "В метаданных плана не обнаружено предупреждений DNS, TLS, firewall или сервисов.",
		"diagnostics.logs":             "Журналы сервисов",
		"diagnostics.logsSummary":      "Просмотр последних записей journald для управляемых сервисов.",
		"diagnostics.serviceUnit":      "Юнит сервиса",
		"diagnostics.lines":            "Строки",
		"diagnostics.loadLogs":         "Загрузить журналы",
		"diagnostics.dns":              "DNS-поиск",
		"diagnostics.dnsSummary":       "Разрешить имя хоста на сервере с помощью",
		"diagnostics.hostname":         "Имя хоста",
		"diagnostics.lookup":           "Найти адрес",
		"diagnostics.ping":             "Проверка связи",
		"diagnostics.pingSummary":      "Проверить доступность хоста с сервера с помощью",
		"diagnostics.host":             "Хост",
		"diagnostics.firewall":         "Firewall",
		"diagnostics.firewallSummary":  "Проверить состояние UFW и планируемые правила через",
		"diagnostics.loadFirewall":     "Загрузить firewall",
		"diagnostics.speedtest":        "Тест скорости",
		"diagnostics.speedtestSummary": "Запустить серверный speedtest-cli/Ookla speedtest из панели.",
		"diagnostics.runSpeedtest":     "Запустить тест скорости",
		"inbounds.title":               "Входящие подключения",
		"inbounds.summaryStart":        "Создание, обновление и удаление",
		"inbounds.add":                 "Добавить подключение",
		"inbounds.editTitle":           "Изменение подключения: {name}",
		"inbounds.nameRequired":        "Укажите имя подключения",
		"inbounds.validationPending":   "Проверка запускается при изменении полей.",
		"inbounds.validationChecking":  "Проверка конфигурации...",
		"inbounds.validationReady":     "Конфигурацию можно сохранить.",
		"inbounds.name":                "Имя",
		"inbounds.transport":           "Транспорт",
		"inbounds.clientProfiles":      "Профили клиентов (JSON)",
		"inbounds.profileHint":         "Используйте добавление профиля для нескольких пользователей или измените JSON вручную.",
		"confirm.deleteInbound":        "Удалить подключение {name}?",
		"routing.title":                "Правила маршрутизации",
		"routing.summaryStart":         "Просмотр, создание, обновление и удаление правил через",
		"routing.add":                  "Добавить правило маршрутизации",
		"routing.edit":                 "Изменить правило маршрутизации",
		"routing.addRule":              "Добавить правило",
		"routing.save":                 "Сохранить правило",
		"routing.delete":               "Удалить правило",
		"routing.nameRequired":         "Укажите имя правила маршрутизации",
		"routing.empty":                "Нажмите «Обновить» или загрузите правила маршрутизации.",
		"routing.match":                "Условие",
		"routing.outbound":             "Направление",
		"routing.presets":              "Готовые наборы",
		"routing.applyPreset":          "Применить готовый набор",
		"routing.loadPresets":          "Загрузить API наборов",
		"routing.loadRaw":              "Загрузить исходный ответ API",
		"confirm.deleteRoutingRule":    "Удалить правило маршрутизации {name}?",
		"clientLinks.title":            "Ссылки клиентов",
		"clientLinks.generateCurrent":  "Создать текущие",
		"clientLinks.connectionTitle":  "Ссылки для подключения клиентов",
		"clientLinks.inboundTitle":     "Ссылки клиентов: {name}",
		"clientLinks.showQR":           "Показать QR",
		"clientLinks.renderingQR":      "Создание QR...",
		"clientLinks.nothingToCopy":    "Пока нечего копировать",
		"clientLinks.copied":           "Скопировано!",
		"modal.addInbound":             "Добавить подключение",
		"modal.closeSymbol":            "×",
		"settings.title":               "Настройки",
		"settings.panelAccess":         "Доступ к панели",
		"settings.panelListen":         "Адрес панели",
		"settings.webBasePath":         "Базовый путь панели",
		"settings.mode":                "Режим",
		"settings.domain":              "Домен",
		"settings.email":               "Email",
		"settings.masqueradeURL":       "URL маскировки",
		"settings.fallbackRoot":        "Резервный каталог",
		"settings.load":                "Загрузить настройки",
		"settings.save":                "Сохранить настройки",
		"runtime.systemResources":      "Ресурсы системы",
		"runtime.refreshTelemetry":     "Обновить телеметрию",
		"runtime.cpuUsage":             "Использование CPU",
		"runtime.memoryUsage":          "Использование памяти",
		"runtime.diskSpace":            "Дисковое пространство",
		"runtime.networkInterfaces":    "Сетевые интерфейсы",
		"runtime.loadNetwork":          "Загрузить статистику сети",
		"runtime.managedProcesses":     "Управляемые процессы",
		"runtime.loadProcesses":        "Загрузить процессы",
		"runtime.listeningPorts":       "Прослушиваемые порты",
		"runtime.loadConnections":      "Загрузить подключения",
		"runtime.diskUsage":            "Использование диска",
		"runtime.loadDisk":             "Загрузить использование диска",
		"service.status":               "Состояние сервисов",
		"service.loadStatus":           "Загрузить состояние сервисов",
		"service.autoRefreshOff":       "Автообновление: выкл.",
		"service.autoRefreshOn":        "Автообновление: вкл. (10 с)",
		"warp.title":                   "Состояние интеграции WARP",
		"warp.connectionSettings":      "Параметры подключения",
		"warp.credentials":             "Учётные данные",
		"warp.proxyRouting":            "Прокси и маршрутизация",
		"warp.endpoint":                "Конечная точка",
		"warp.privateKey":              "Приватный ключ WireGuard",
		"warp.peerKey":                 "Публичный ключ узла",
		"warp.license":                 "Необязательная лицензия WARP+",
		"warp.localAddress":            "Локальный адрес",
		"warp.reserved":                "Зарезервированные байты",
		"warp.socksListen":             "Адрес SOCKS",
		"warp.socksPort":               "Порт SOCKS",
		"warp.load":                    "Загрузить WARP",
		"warp.save":                    "Сохранить конфигурацию WARP",
	})
}

func installTranslationCatalog(locale string, entries map[string]string) {
	catalog := translationCatalogs[locale]
	for key, value := range entries {
		catalog[key] = value
	}
}
