package panel

import "github.com/mikkelchokolate/Veil/internal/protocols"

func init() {
	installTranslationCatalog(LocaleEnglish, map[string]string{
		"common.actions":                                "Actions",
		"common.current":                                "Current",
		"common.expires":                                "Expires",
		"common.yes":                                    "yes",
		"common.no":                                     "no",
		"common.close":                                  "Close",
		"common.ok":                                     "OK",
		"common.consoleCleared":                         "Console cleared.",
		"common.error":                                  "Error: {error}",
		"status.notLoaded":                              "Not loaded",
		"status.notGenerated":                           "Not generated",
		"status.notPlanned":                             "Not planned",
		"status.notStarted":                             "Not started",
		"status.noUsers":                                "No users registered",
		"status.noSessions":                             "No active sessions",
		"status.loadingUsers":                           "Loading users...",
		"status.loadingSessions":                        "Loading sessions...",
		"status.loadingPath":                            "Loading {path}...",
		"status.accessDenied":                           "Access Denied (Admin role required)",
		"status.requestFailed":                          "Request failed: {error}",
		"status.loadFailed":                             "Load failed: {error}",
		"status.copyFailed":                             "Copy failed: {error}",
		"status.downloadFailed":                         "Download failed: {error}",
		"status.restoreCancelled":                       "Restore cancelled",
		"status.restoreTimedOut":                        "Restore job polling timed out",
		"status.unknownError":                           "unknown error",
		"placeholder.domain":                            "vpn.example.com",
		"placeholder.hostname":                          "example.com",
		"placeholder.ipAddress":                         "8.8.8.8",
		"placeholder.userPassword":                      "Password",
		"placeholder.keepPassword":                      "Leave blank to keep current",
		"dashboard.systemOnline":                        "System Online",
		"dashboard.coreUptime":                          "Core Uptime",
		"dashboard.monitoringSummary":                   "Continuous service orchestration and connection monitoring",
		"dashboard.serviceLinks":                        "Service Links",
		"dashboard.endpoints":                           "Endpoints",
		"token.title":                                   "API token",
		"token.summaryStart":                            "If the server was started with",
		"token.summaryMiddle":                           ", paste the token here. The browser stores it only in",
		"token.summaryEnd":                              "and sends it as",
		"token.optional":                                "Optional API token",
		"token.toggleVisibility":                        "Toggle visibility",
		"version.title":                                 "Version",
		"version.summaryStart":                          "Veil server version and runtime info fetched directly from",
		"version.load":                                  "Load version",
		"version.update":                                "Update panel",
		"version.output":                                "Runtime Output",
		"version.startingUpdate":                        "Starting self-update... Fetching latest release, verifying checksums and installing binary. Please wait, this will take a moment...",
		"version.updateFailed":                          "UPDATE FAILED:\n{details}",
		"version.updateStaged":                          "Update staged successfully! Restarting panel service to apply...",
		"version.waitingRestart":                        "Staging completed. Waiting for service restart and health check... (Attempt {attempt}/{max})",
		"version.backOnline":                            "SERVICE BACK ONLINE!\n\n{details}",
		"version.restartSlow":                           "Restart is taking longer than expected. Please refresh the page manually in a few seconds to check status.",
		"installPreview.title":                          "Panel install preview",
		"installPreview.summaryStart":                   "Preview a Panel-only",
		"installPreview.summaryEnd":                     "install without writing anything. Choose Caddy only when the Panel should be reachable by HTTPS domain without a port.",
		"installPreview.submit":                         "Preview Panel install",
		"installPreview.output":                         "Profile Output Preview",
		"installPreview.caddyRequired":                  "Domain and email are required for Caddy Panel access",
		"users.managementTitle":                         "User Management",
		"users.managementSummary":                       "Manage administrative and viewer credentials. Viewer accounts can view diagnostics, settings, and stats, but cannot add/delete inbounds, modify routing rules, or apply changes.",
		"users.activeSessions":                          "Active Sessions",
		"users.sessionsSummary":                         "Review browser sessions and revoke stale operator access. The current session is marked so it is harder to lock yourself out accidentally.",
		"users.loadSessions":                            "Load sessions",
		"users.apiTokenRotation":                        "API Token Rotation",
		"users.apiTokenSummaryStart":                    "Generate a replacement API token, update",
		"users.apiTokenSummaryEnd":                      "in your service environment or restart command, then restart the Panel. Existing browser sessions are managed above.",
		"users.generateToken":                           "Generate token",
		"users.copyToken":                               "Copy generated token",
		"users.noGeneratedToken":                        "No generated token",
		"users.statusOutput":                            "Status Output",
		"users.revoke":                                  "Revoke",
		"users.revokeSelf":                              "Revoke self",
		"users.edit":                                    "Edit",
		"users.user":                                    "User",
		"users.sessionRevokeFailed":                     "Session revoke failed: {error}",
		"users.generatedToken":                          "Generated replacement token:\n{token}\n\nUpdate VEIL_API_TOKEN in /etc/veil/veil.env or the --auth-token value, restart veil.service, then update API clients and this browser token field.",
		"users.generateTokenFirst":                      "Generate a token first",
		"users.tokenCopied":                             "Copied generated token to clipboard",
		"users.updating":                                "Updating user...",
		"users.creating":                                "Creating user...",
		"users.passwordRequired":                        "Password is required for new users",
		"users.updated":                                 "User updated successfully",
		"users.created":                                 "User created successfully",
		"users.deleting":                                "Deleting user...",
		"users.deleteFailed":                            "Error deleting user: {error}",
		"users.deleted":                                 "User deleted successfully",
		"backups.disasterRecovery":                      "Disaster Recovery",
		"backups.summaryStart":                          "Archives are encrypted with the server-side scheduled backup passphrase. Configure it once with",
		"backups.summaryEnd":                            "; the browser never receives the passphrase.",
		"backups.daily":                                 "Daily copies",
		"backups.weekly":                                "Weekly copies",
		"backups.monthly":                               "Monthly copies",
		"backups.create":                                "Create encrypted backup",
		"backups.applyRetention":                        "Apply retention",
		"backups.created":                               "Created",
		"backups.archive":                               "Archive",
		"backups.size":                                  "Size",
		"backups.encrypted":                             "Encrypted",
		"backups.verify":                                "Verify",
		"backups.loading":                               "Loading backups...",
		"backups.empty":                                 "No managed backup archives",
		"backups.creating":                              "Creating and verifying encrypted backup...",
		"backups.verifying":                             "Verifying {name}...",
		"confirm.pruneBackups":                          "Apply the displayed daily, weekly, and monthly retention policy? Deleted archives cannot be recovered from this host.",
		"confirm.restoreBackupPrompt":                   "Restore overwrites live state and revokes existing sessions. Type the archive name to continue:\n{name}",
		"apply.planTitle":                               "Apply plan",
		"apply.planSummary":                             "Validate current management state and show staged config/reload actions before any real service changes:",
		"apply.healthSummary":                           "Service reload also runs fixed health checks and automatically rolls live configs back if reload or health fails.",
		"apply.buildPlan":                               "Build apply plan",
		"apply.stagedFiles":                             "Apply staged files",
		"apply.liveConfigs":                             "Apply live configs",
		"apply.reloadServices":                          "Reload and health check services",
		"apply.safePreview":                             "Safe apply preview",
		"apply.previewSummary":                          "Shows file-level config changes, runtime actions, and DNS/TLS/firewall warnings without exposing generated config contents or secrets.",
		"apply.buildFirst":                              "Safety warnings: build a plan first",
		"apply.operation":                               "Operation",
		"apply.target":                                  "Target",
		"apply.interruptionRisk":                        "Interruption risk",
		"apply.rollback":                                "Rollback",
		"apply.validatedBy":                             "Validated by",
		"apply.previewEmpty":                            "Build a plan to preview managed files and runtime actions.",
		"apply.noOperations":                            "No managed files or runtime actions were reported.",
		"apply.historyStage":                            "History stage",
		"apply.historySuccess":                          "History success",
		"apply.historyLimit":                            "History limit",
		"apply.loadHistory":                             "Load apply history",
		"apply.runtimeNotPlanned":                       "Runtime units: not planned",
		"apply.runtimeNone":                             "Runtime units: none required",
		"apply.runtimeList":                             "Runtime units: {runtimes}",
		"apply.warningSummary":                          "Safety warnings: {warnings}",
		"apply.warningInvalid":                          "Plan is invalid; fix validation errors before applying.",
		"apply.warningErrors":                           "Plan errors are present in the raw output.",
		"apply.warningConnectionDrop":                   "One or more service restarts can drop active proxy connections.",
		"apply.warningFirewall":                         "Firewall changes can lock out remote access; verify SSH and provider console access before applying.",
		"apply.warningDNS":                              "DNS changes depend on public records and propagation before client links work.",
		"apply.warningTLS":                              "TLS changes require valid domain reachability and certificate issuance.",
		"apply.warningServiceRestart":                   "Service reload or restart can interrupt active proxy sessions.",
		"apply.warningNone":                             "No DNS/TLS/firewall/service warnings detected in plan metadata.",
		"diagnostics.logs":                              "Service logs",
		"diagnostics.logsSummary":                       "View recent journald logs for managed services.",
		"diagnostics.serviceUnit":                       "Service unit",
		"diagnostics.lines":                             "Lines",
		"diagnostics.loadLogs":                          "Load logs",
		"diagnostics.dns":                               "DNS lookup",
		"diagnostics.dnsSummary":                        "Resolve a hostname from the server using",
		"diagnostics.hostname":                          "Hostname",
		"diagnostics.lookup":                            "Lookup hostname",
		"diagnostics.ping":                              "Ping",
		"diagnostics.pingSummary":                       "Ping a host from the server using",
		"diagnostics.host":                              "Host",
		"diagnostics.firewall":                          "Firewall",
		"diagnostics.firewallSummary":                   "Check UFW firewall status and planned rules from",
		"diagnostics.loadFirewall":                      "Load firewall",
		"diagnostics.speedtest":                         "Speedtest",
		"diagnostics.speedtestSummary":                  "Run server-side speedtest-cli/Ookla speedtest from the panel.",
		"diagnostics.runSpeedtest":                      "Run speedtest",
		"diagnostics.notStarted":                        "Not started",
		"diagnostics.count":                             "Count (1-10)",
		"diagnostics.hostnameRequired":                  "Hostname is required",
		"diagnostics.hostRequired":                      "Host is required",
		"validation.dns_unresolved.message":             "Configured domain does not resolve",
		"validation.dns_unresolved.remediation":         "Create or correct the DNS record before applying this configuration.",
		"validation.name_required.message":              "Enabled inbound requires a name",
		"validation.name_required.remediation":          "Choose a unique inbound name.",
		"validation.unsupported_protocol.message":       "Unsupported inbound protocol",
		"validation.unsupported_protocol.remediation":   "Choose one of the protocols offered by Veil.",
		"validation.transport_required.message":         "Enabled inbound requires a transport",
		"validation.transport_required.remediation":     "Choose a transport supported by this protocol.",
		"validation.unsupported_transport.message":      "Transport is not supported by this protocol",
		"validation.unsupported_transport.remediation":  "Choose a transport listed for the selected protocol.",
		"validation.port_invalid.message":               "Inbound port must be between 1 and 65535",
		"validation.port_invalid.remediation":           "Choose a valid TCP or UDP port.",
		"validation.duplicate_binding.message":          "This transport and port are already assigned to another inbound",
		"validation.duplicate_binding.remediation":      "Choose another port or disable the other inbound.",
		"validation.reserved_panel_port.message":        "This TCP port is reserved by the Panel",
		"validation.reserved_panel_port.remediation":    "Choose another inbound port or move the Panel listener.",
		"validation.port_probe_failed.message":          "Veil could not check whether this port is available",
		"validation.port_probe_failed.remediation":      "Check host permissions and retry validation.",
		"validation.port_in_use.message":                "This port is already in use",
		"validation.port_in_use.remediation":            "Stop the conflicting service or choose another port.",
		"validation.runtime_binary_missing.message":     "A required protocol runtime is not installed",
		"validation.runtime_binary_missing.remediation": "Install the protocol runtime before applying.",
		"validation.runtime_unit_missing.message":       "A required managed systemd unit is unavailable",
		"validation.runtime_unit_missing.remediation":   "Install or repair Veil managed service units.",
		"validation.domain_required.message":            "This protocol requires a public domain",
		"validation.domain_required.remediation":        "Set the domain that resolves to this host.",
		"validation.email_required.message":             "This protocol requires an email address",
		"validation.email_required.remediation":         "Set the ACME contact email.",
		"validation.credential_required.message":        "This inbound has no usable client credential",
		"validation.credential_required.remediation":    "Set an inbound credential or enable a client profile with credentials.",
		"inbounds.title":                                "Inbounds",
		"inbounds.summaryStart":                         "Create, update, or delete",
		"inbounds.add":                                  "Add Inbound",
		"inbounds.editTitle":                            "Edit Inbound: {name}",
		"inbounds.nameRequired":                         "Inbound name is required",
		"inbounds.validationPending":                    "Validation runs as fields change.",
		"inbounds.validationChecking":                   "Checking configuration...",
		"inbounds.validationReady":                      "Configuration is ready to save.",
		"inbounds.name":                                 "Name",
		"inbounds.transport":                            "Transport",
		"inbounds.clientProfiles":                       "Client profiles (JSON)",
		"inbounds.profileHint":                          "Use Add profile for multiple users on one Inbound, or edit JSON directly.",
		"inbounds.clients":                              "Clients",
		"inbounds.empty":                                "No inbounds configured. Click Add Inbound to start.",
		"inbounds.refresh":                              "Refresh List",
		"inbounds.naiveUsername":                        "Naive Username",
		"inbounds.naivePassword":                        "Naive Password",
		"inbounds.fallbackRoot":                         "Fallback Root",
		"inbounds.hysteria2Password":                    "Hysteria2 Password",
		"inbounds.masqueradeURL":                        "Masquerade URL",
		"inbounds.hysteria2Insecure":                    "Insecure mode (allow self-signed server certificate)",
		"inbounds.olcrtcAuth":                           "olcRTC Auth Provider",
		"inbounds.olcrtcTransport":                      "olcRTC Transport",
		"inbounds.olcrtcRoomID":                         "olcRTC Room ID",
		"inbounds.clientProfile":                        "Client profile",
		"inbounds.addProfile":                           "Add profile",
		"inbounds.generateProfile":                      "Generate profile",
		"inbounds.profileNameRequired":                  "Client profile name is required",
		"inbounds.profilesInvalid":                      "Client profiles must be valid JSON: {error}",
		"confirm.deleteInbound":                         "Delete inbound {name}?",
		"routing.title":                                 "Routing rules",
		"routing.summaryStart":                          "List, create, update, or delete routing rules through",
		"routing.add":                                   "Add Routing Rule",
		"routing.edit":                                  "Edit Routing Rule",
		"routing.addRule":                               "Add Rule",
		"routing.save":                                  "Save routing rule",
		"routing.delete":                                "Delete routing rule",
		"routing.nameRequired":                          "Routing rule name is required",
		"routing.empty":                                 "Click 'Refresh' or load to display routing rules.",
		"routing.match":                                 "Match",
		"routing.outbound":                              "Outbound",
		"routing.presets":                               "Preset selectors",
		"routing.applyPreset":                           "Apply routing preset",
		"routing.loadPresets":                           "Load Presets API",
		"routing.loadRaw":                               "Load Raw API Response",
		"routing.matchRule":                             "Match Rule",
		"routing.geoStart":                              "Russian geo/site data is pulled from",
		"routing.geoEnd":                                "when a Russia-aware preset is applied.",
		"routing.clearConsole":                          "Clear Console",
		"confirm.deleteRoutingRule":                     "Delete routing rule {name}?",
		"clientLinks.title":                             "Client links",
		"clientLinks.generateCurrent":                   "Generate current",
		"clientLinks.load":                              "Load client links",
		"clientLinks.openExport":                        "Open QR/export modal",
		"clientLinks.loadBase64":                        "Load base64 subscription",
		"clientLinks.loadRaw":                           "Load raw subscription",
		"clientLinks.downloadJSON":                      "Download links JSON",
		"clientLinks.downloadBase64":                    "Download base64 subscription",
		"clientLinks.downloadRaw":                       "Download raw subscription",
		"clientLinks.downloadClientConfigs":             "Download client configs",
		"clientLinks.copyOutput":                        "Copy output",
		"clientLinks.qrPrivacy":                         "QR codes are rendered locally by the Panel API; connection strings are never sent to a third-party QR service.",
		"clientLinks.modalSummary":                      "Copy, download, or scan the connection strings below. QR images are generated by",
		"clientLinks.loading":                           "Loading connection links...",
		"clientLinks.failed":                            "Failed to load links",
		"clientLinks.empty":                             "No connection links available for this inbound. Make sure the inbound is enabled and global settings are saved.",
		"clientLinks.loadingClientConfigs":              "Loading client configs...",
		"clientLinks.noClientConfigs":                   "No client configs available",
		"clientLinks.downloaded":                        "Downloaded {filename}",
		"clientLinks.clientConfigsFailed":               "Client config download failed: {error}",
		"clientLinks.downloadingJSON":                   "Downloading client links JSON...",
		"clientLinks.downloading":                       "Downloading {path}...",
		"clientLinks.copiedOutput":                      "Copied to clipboard",
		"clientLinks.copyFailed":                        "Copy failed: {error}",
		"clientLinks.port":                              "Port {port}",
		"clientLinks.copyFailedAlert":                   "Failed to copy link: {error}",
		"clientLinks.qrAlt":                             "Client link QR code",
		"clientLinks.qrFailed":                          "QR render failed: {error}",
		"clientLinks.connectionTitle":                   "Client Connection Links",
		"clientLinks.inboundTitle":                      "Client Links: {name}",
		"clientLinks.showQR":                            "Show QR",
		"clientLinks.renderingQR":                       "Rendering QR...",
		"clientLinks.nothingToCopy":                     "Nothing to copy yet",
		"clientLinks.copied":                            "Copied!",
		"modal.addInbound":                              "Add Inbound",
		"modal.closeSymbol":                             "×",
		"settings.title":                                "Settings",
		"settings.panelAccess":                          "Panel access",
		"settings.panelListen":                          "Panel listen",
		"settings.webBasePath":                          "Web base path",
		"settings.mode":                                 "Mode",
		"settings.domain":                               "Domain",
		"settings.email":                                "Email",
		"settings.masqueradeURL":                        "Masquerade URL",
		"settings.fallbackRoot":                         "Fallback root",
		"settings.load":                                 "Load settings",
		"settings.save":                                 "Save settings",
		"runtime.systemResources":                       "System resources",
		"runtime.refreshTelemetry":                      "Refresh telemetry",
		"runtime.load":                                  "Load",
		"runtime.ram":                                   "RAM",
		"runtime.disk":                                  "Disk",
		"runtime.telemetrySummary":                      "CPU, memory, disk, load average from",
		"runtime.rawJSON":                               "Raw JSON",
		"runtime.cpuUsage":                              "CPU Usage",
		"runtime.memoryUsage":                           "Memory Usage",
		"runtime.diskSpace":                             "Disk Space",
		"runtime.networkInterfaces":                     "Network interfaces",
		"runtime.networkSummary":                        "RX/TX bytes and packets from",
		"runtime.interface":                             "Interface",
		"runtime.bytesReceived":                         "Bytes Received (RX)",
		"runtime.bytesTransmitted":                      "Bytes Transmitted (TX)",
		"runtime.packets":                               "Packets (RX / TX)",
		"runtime.noInterfaces":                          "No interfaces loaded. Click refresh.",
		"runtime.loadNetwork":                           "Load network stats",
		"runtime.managedProcesses":                      "Managed processes",
		"runtime.processesSummary":                      "Running service processes from",
		"runtime.pid":                                   "PID",
		"runtime.cpuPercent":                            "CPU %",
		"runtime.memoryRSS":                             "Memory (RSS)",
		"runtime.uptime":                                "Uptime",
		"runtime.noProcesses":                           "No processes loaded.",
		"runtime.loadProcesses":                         "Load processes",
		"runtime.listeningPorts":                        "Listening ports",
		"runtime.connectionsSummary":                    "TCP/UDP listening sockets from",
		"runtime.loadConnections":                       "Load connections",
		"runtime.diskUsage":                             "Disk usage",
		"runtime.diskSummary":                           "Directory sizes for Veil paths from",
		"runtime.loadDisk":                              "Load disk usage",
		"service.status":                                "Service status",
		"service.loadStatus":                            "Load service status",
		"service.autoRefreshOff":                        "Auto-refresh: OFF",
		"service.autoRefreshOn":                         "Auto-refresh: ON (10s)",
		"telemetry.autoRefreshOff":                      "Auto-refresh: OFF",
		"telemetry.autoRefreshOn":                       "Auto-refresh: ON (1s)",
		"service.restart":                               "Restart {service}",
		"warp.title":                                    "WARP Integration Status",
		"warp.summary":                                  "Configure the optional sing-box WireGuard/WARP sidecar through",
		"warp.redactedSummary":                          "Redacted private/license keys are preserved by the API when saved back as",
		"warp.enabledHelp":                              "Enable or disable the background WireGuard/WARP service",
		"warp.connectionSettings":                       "Connection settings",
		"warp.credentials":                              "Credentials",
		"warp.proxyRouting":                             "Proxy & Routing",
		"warp.endpoint":                                 "Endpoint",
		"warp.privateKey":                               "WireGuard private key",
		"warp.privateKeyShort":                          "Private key",
		"warp.peerKey":                                  "Peer public key",
		"warp.license":                                  "Optional WARP+ license",
		"warp.licenseKey":                               "License key",
		"warp.localAddress":                             "Local address",
		"warp.reserved":                                 "Reserved bytes",
		"warp.socksListen":                              "SOCKS listen",
		"warp.socksPort":                                "SOCKS port",
		"warp.load":                                     "Load WARP",
		"warp.save":                                     "Save WARP config",
	})

	installTranslationCatalog(LocaleRussian, map[string]string{
		"common.actions":                                "Действия",
		"common.current":                                "Текущая",
		"common.expires":                                "Истекает",
		"common.yes":                                    "да",
		"common.no":                                     "нет",
		"common.close":                                  "Закрыть",
		"common.ok":                                     "Готово",
		"common.consoleCleared":                         "Консоль очищена.",
		"common.error":                                  "Ошибка: {error}",
		"status.notLoaded":                              "Не загружено",
		"status.notGenerated":                           "Не создано",
		"status.notPlanned":                             "Не запланировано",
		"status.notStarted":                             "Не запущено",
		"status.noUsers":                                "Пользователей нет",
		"status.noSessions":                             "Активных сессий нет",
		"status.loadingUsers":                           "Загрузка пользователей...",
		"status.loadingSessions":                        "Загрузка сессий...",
		"status.loadingPath":                            "Загрузка {path}...",
		"status.accessDenied":                           "Доступ запрещён: требуется роль администратора",
		"status.requestFailed":                          "Ошибка запроса: {error}",
		"status.loadFailed":                             "Ошибка загрузки: {error}",
		"status.copyFailed":                             "Ошибка копирования: {error}",
		"status.downloadFailed":                         "Ошибка скачивания: {error}",
		"status.restoreCancelled":                       "Восстановление отменено",
		"status.restoreTimedOut":                        "Истекло время ожидания восстановления",
		"status.unknownError":                           "неизвестная ошибка",
		"placeholder.domain":                            "vpn.example.com",
		"placeholder.hostname":                          "example.com",
		"placeholder.ipAddress":                         "8.8.8.8",
		"placeholder.userPassword":                      "Пароль",
		"placeholder.keepPassword":                      "Оставьте пустым, чтобы сохранить текущий",
		"dashboard.systemOnline":                        "Система в сети",
		"dashboard.coreUptime":                          "Время работы",
		"dashboard.monitoringSummary":                   "Непрерывное управление сервисами и наблюдение за подключениями",
		"dashboard.serviceLinks":                        "Ссылки сервисов",
		"dashboard.endpoints":                           "Конечные точки",
		"token.title":                                   "API-токен",
		"token.summaryStart":                            "Если сервер запущен с",
		"token.summaryMiddle":                           ", вставьте токен сюда. Браузер хранит его только в",
		"token.summaryEnd":                              "и отправляет в заголовке",
		"token.optional":                                "Необязательный API-токен",
		"token.toggleVisibility":                        "Показать или скрыть",
		"version.title":                                 "Версия",
		"version.summaryStart":                          "Версия сервера Veil и сведения о среде загружаются из",
		"version.load":                                  "Загрузить версию",
		"version.update":                                "Обновить панель",
		"version.output":                                "Результат",
		"version.startingUpdate":                        "Запуск самообновления... Загружается последний выпуск, проверяются контрольные суммы и устанавливается бинарный файл. Подождите.",
		"version.updateFailed":                          "ОБНОВЛЕНИЕ НЕ ВЫПОЛНЕНО:\n{details}",
		"version.updateStaged":                          "Обновление подготовлено. Перезапускаем сервис панели...",
		"version.waitingRestart":                        "Подготовка завершена. Ожидаем перезапуск и проверку состояния... (попытка {attempt}/{max})",
		"version.backOnline":                            "СЕРВИС СНОВА В СЕТИ\n\n{details}",
		"version.restartSlow":                           "Перезапуск занимает больше времени, чем ожидалось. Обновите страницу вручную через несколько секунд.",
		"installPreview.title":                          "Предпросмотр установки панели",
		"installPreview.summaryStart":                   "Предпросмотр установки только панели по профилю",
		"installPreview.summaryEnd":                     "без записи файлов. Выбирайте Caddy, только если панель должна открываться по HTTPS-домену без указания порта.",
		"installPreview.submit":                         "Предпросмотр установки",
		"installPreview.output":                         "Предпросмотр профиля",
		"installPreview.caddyRequired":                  "Для доступа через Caddy требуются домен и email",
		"users.managementTitle":                         "Управление пользователями",
		"users.managementSummary":                       "Управляйте учётными данными администраторов и наблюдателей. Наблюдатели могут просматривать диагностику, настройки и статистику, но не могут менять подключения, маршруты или применять конфигурацию.",
		"users.activeSessions":                          "Активные сессии",
		"users.sessionsSummary":                         "Проверяйте сессии браузера и отзывайте устаревший доступ. Текущая сессия отмечена, чтобы снизить риск случайной блокировки.",
		"users.loadSessions":                            "Загрузить сессии",
		"users.apiTokenRotation":                        "Ротация API-токена",
		"users.apiTokenSummaryStart":                    "Создайте новый API-токен, обновите",
		"users.apiTokenSummaryEnd":                      "в окружении сервиса или команде запуска, затем перезапустите панель. Сессии браузера управляются выше.",
		"users.generateToken":                           "Создать токен",
		"users.copyToken":                               "Копировать созданный токен",
		"users.noGeneratedToken":                        "Токен ещё не создан",
		"users.statusOutput":                            "Состояние",
		"users.revoke":                                  "Отозвать",
		"users.revokeSelf":                              "Отозвать текущую",
		"users.edit":                                    "Изменить",
		"users.user":                                    "Пользователь",
		"users.sessionRevokeFailed":                     "Не удалось отозвать сессию: {error}",
		"users.generatedToken":                          "Создан новый API-токен:\n{token}\n\nОбновите VEIL_API_TOKEN в /etc/veil/veil.env или значение --auth-token, перезапустите veil.service, затем обновите API-клиенты и поле токена в этом браузере.",
		"users.generateTokenFirst":                      "Сначала создайте токен",
		"users.tokenCopied":                             "Созданный токен скопирован",
		"users.updating":                                "Обновление пользователя...",
		"users.creating":                                "Создание пользователя...",
		"users.passwordRequired":                        "Для нового пользователя требуется пароль",
		"users.updated":                                 "Пользователь обновлён",
		"users.created":                                 "Пользователь создан",
		"users.deleting":                                "Удаление пользователя...",
		"users.deleteFailed":                            "Не удалось удалить пользователя: {error}",
		"users.deleted":                                 "Пользователь удалён",
		"backups.disasterRecovery":                      "Аварийное восстановление",
		"backups.summaryStart":                          "Архивы шифруются серверной парольной фразой плановых копий. Настройте её один раз командой",
		"backups.summaryEnd":                            "; браузер никогда не получает парольную фразу.",
		"backups.daily":                                 "Дневные копии",
		"backups.weekly":                                "Недельные копии",
		"backups.monthly":                               "Месячные копии",
		"backups.create":                                "Создать зашифрованную копию",
		"backups.applyRetention":                        "Применить хранение",
		"backups.created":                               "Создана",
		"backups.archive":                               "Архив",
		"backups.size":                                  "Размер",
		"backups.encrypted":                             "Зашифрован",
		"backups.verify":                                "Проверить",
		"backups.loading":                               "Загрузка резервных копий...",
		"backups.empty":                                 "Управляемых архивов нет",
		"backups.creating":                              "Создание и проверка зашифрованной резервной копии...",
		"backups.verifying":                             "Проверка {name}...",
		"confirm.pruneBackups":                          "Применить показанную политику дневного, недельного и месячного хранения? Удалённые архивы нельзя восстановить с этого хоста.",
		"confirm.restoreBackupPrompt":                   "Восстановление перезапишет рабочее состояние и отзовёт существующие сессии. Введите имя архива для продолжения:\n{name}",
		"apply.planTitle":                               "План применения",
		"apply.planSummary":                             "Проверьте текущее состояние и просмотрите действия с конфигурацией и сервисами до реальных изменений:",
		"apply.healthSummary":                           "Перезагрузка сервисов включает фиксированные проверки здоровья и автоматически откатывает конфигурацию при ошибке.",
		"apply.buildPlan":                               "Построить план",
		"apply.stagedFiles":                             "Применить подготовленные файлы",
		"apply.liveConfigs":                             "Применить рабочие конфигурации",
		"apply.reloadServices":                          "Перезагрузить и проверить сервисы",
		"apply.safePreview":                             "Безопасный предпросмотр",
		"apply.previewSummary":                          "Показывает изменения файлов, действия сервисов и предупреждения DNS, TLS и firewall без раскрытия конфигураций и секретов.",
		"apply.buildFirst":                              "Предупреждения безопасности: сначала постройте план",
		"apply.operation":                               "Операция",
		"apply.target":                                  "Цель",
		"apply.interruptionRisk":                        "Риск прерывания",
		"apply.rollback":                                "Откат",
		"apply.validatedBy":                             "Проверено",
		"apply.previewEmpty":                            "Постройте план для предпросмотра файлов и действий сервисов.",
		"apply.noOperations":                            "Управляемые файлы и действия сервисов не обнаружены.",
		"apply.historyStage":                            "Этап истории",
		"apply.historySuccess":                          "Результат истории",
		"apply.historyLimit":                            "Лимит истории",
		"apply.loadHistory":                             "Загрузить историю",
		"apply.runtimeNotPlanned":                       "Сервисы: план ещё не построен",
		"apply.runtimeNone":                             "Сервисы: перезапуск не требуется",
		"apply.runtimeList":                             "Сервисы: {runtimes}",
		"apply.warningSummary":                          "Предупреждения безопасности: {warnings}",
		"apply.warningInvalid":                          "План недействителен; исправьте ошибки проверки перед применением.",
		"apply.warningErrors":                           "Исходный ответ содержит ошибки плана.",
		"apply.warningConnectionDrop":                   "Перезапуск одного или нескольких сервисов может разорвать активные прокси-соединения.",
		"apply.warningFirewall":                         "Изменения firewall могут заблокировать удалённый доступ; перед применением проверьте SSH и консоль провайдера.",
		"apply.warningDNS":                              "Для работы клиентских ссылок изменения DNS требуют публичных записей и времени на распространение.",
		"apply.warningTLS":                              "Для изменений TLS нужны доступный домен и успешный выпуск сертификата.",
		"apply.warningServiceRestart":                   "Перезагрузка или перезапуск сервиса может прервать активные прокси-сессии.",
		"apply.warningNone":                             "В метаданных плана не обнаружено предупреждений DNS, TLS, firewall или сервисов.",
		"diagnostics.logs":                              "Журналы сервисов",
		"diagnostics.logsSummary":                       "Просмотр последних записей journald для управляемых сервисов.",
		"diagnostics.serviceUnit":                       "Юнит сервиса",
		"diagnostics.lines":                             "Строки",
		"diagnostics.loadLogs":                          "Загрузить журналы",
		"diagnostics.dns":                               "DNS-поиск",
		"diagnostics.dnsSummary":                        "Разрешить имя хоста на сервере с помощью",
		"diagnostics.hostname":                          "Имя хоста",
		"diagnostics.lookup":                            "Найти адрес",
		"diagnostics.ping":                              "Проверка связи",
		"diagnostics.pingSummary":                       "Проверить доступность хоста с сервера с помощью",
		"diagnostics.host":                              "Хост",
		"diagnostics.firewall":                          "Firewall",
		"diagnostics.firewallSummary":                   "Проверить состояние UFW и планируемые правила через",
		"diagnostics.loadFirewall":                      "Загрузить firewall",
		"diagnostics.speedtest":                         "Тест скорости",
		"diagnostics.speedtestSummary":                  "Запустить серверный speedtest-cli/Ookla speedtest из панели.",
		"diagnostics.runSpeedtest":                      "Запустить тест скорости",
		"diagnostics.notStarted":                        "Не запущено",
		"diagnostics.count":                             "Количество (1-10)",
		"diagnostics.hostnameRequired":                  "Укажите имя хоста",
		"diagnostics.hostRequired":                      "Укажите хост",
		"validation.dns_unresolved.message":             "Настроенный домен не разрешается",
		"validation.dns_unresolved.remediation":         "Создайте или исправьте DNS-запись перед применением конфигурации.",
		"validation.name_required.message":              "Для включённого подключения требуется имя",
		"validation.name_required.remediation":          "Выберите уникальное имя подключения.",
		"validation.unsupported_protocol.message":       "Протокол подключения не поддерживается",
		"validation.unsupported_protocol.remediation":   "Выберите один из протоколов, доступных в Veil.",
		"validation.transport_required.message":         "Для включённого подключения требуется транспорт",
		"validation.transport_required.remediation":     "Выберите транспорт, поддерживаемый этим протоколом.",
		"validation.unsupported_transport.message":      "Транспорт не поддерживается этим протоколом",
		"validation.unsupported_transport.remediation":  "Выберите транспорт из списка для выбранного протокола.",
		"validation.port_invalid.message":               "Порт подключения должен быть от 1 до 65535",
		"validation.port_invalid.remediation":           "Выберите корректный TCP- или UDP-порт.",
		"validation.duplicate_binding.message":          "Этот транспорт и порт уже назначены другому подключению",
		"validation.duplicate_binding.remediation":      "Выберите другой порт или отключите другое подключение.",
		"validation.reserved_panel_port.message":        "Этот TCP-порт зарезервирован панелью",
		"validation.reserved_panel_port.remediation":    "Выберите другой порт подключения или перенесите панель.",
		"validation.port_probe_failed.message":          "Veil не удалось проверить доступность порта",
		"validation.port_probe_failed.remediation":      "Проверьте права на хосте и повторите проверку.",
		"validation.port_in_use.message":                "Этот порт уже используется",
		"validation.port_in_use.remediation":            "Остановите конфликтующий сервис или выберите другой порт.",
		"validation.runtime_binary_missing.message":     "Требуемая среда протокола не установлена",
		"validation.runtime_binary_missing.remediation": "Установите среду протокола перед применением.",
		"validation.runtime_unit_missing.message":       "Требуемый управляемый systemd-юнит недоступен",
		"validation.runtime_unit_missing.remediation":   "Установите или восстановите управляемые юниты Veil.",
		"validation.domain_required.message":            "Для этого протокола требуется публичный домен",
		"validation.domain_required.remediation":        "Укажите домен, который разрешается на этот хост.",
		"validation.email_required.message":             "Для этого протокола требуется email",
		"validation.email_required.remediation":         "Укажите контактный email для ACME.",
		"validation.credential_required.message":        "У подключения нет пригодных учётных данных клиента",
		"validation.credential_required.remediation":    "Укажите учётные данные подключения или включите профиль клиента с учётными данными.",
		"inbounds.title":                                "Входящие подключения",
		"inbounds.summaryStart":                         "Создание, обновление и удаление",
		"inbounds.add":                                  "Добавить подключение",
		"inbounds.editTitle":                            "Изменение подключения: {name}",
		"inbounds.nameRequired":                         "Укажите имя подключения",
		"inbounds.validationPending":                    "Проверка запускается при изменении полей.",
		"inbounds.validationChecking":                   "Проверка конфигурации...",
		"inbounds.validationReady":                      "Конфигурацию можно сохранить.",
		"inbounds.name":                                 "Имя",
		"inbounds.transport":                            "Транспорт",
		"inbounds.clientProfiles":                       "Профили клиентов (JSON)",
		"inbounds.profileHint":                          "Используйте добавление профиля для нескольких пользователей или измените JSON вручную.",
		"inbounds.clients":                              "Клиенты",
		"inbounds.empty":                                "Подключений пока нет. Нажмите «Добавить подключение».",
		"inbounds.refresh":                              "Обновить список",
		"inbounds.naiveUsername":                        "Имя пользователя Naive",
		"inbounds.naivePassword":                        "Пароль Naive",
		"inbounds.fallbackRoot":                         "Резервный каталог",
		"inbounds.hysteria2Password":                    "Пароль Hysteria2",
		"inbounds.masqueradeURL":                        "URL маскировки",
		"inbounds.hysteria2Insecure":                    "Небезопасный режим (разрешить самоподписанный сертификат)",
		"inbounds.olcrtcAuth":                           "Провайдер авторизации olcRTC",
		"inbounds.olcrtcTransport":                      "Транспорт olcRTC",
		"inbounds.olcrtcRoomID":                         "ID комнаты olcRTC",
		"inbounds.clientProfile":                        "Профиль клиента",
		"inbounds.addProfile":                           "Добавить профиль",
		"inbounds.generateProfile":                      "Создать профиль",
		"inbounds.profileNameRequired":                  "Укажите имя профиля клиента",
		"inbounds.profilesInvalid":                      "Профили клиентов должны быть корректным JSON: {error}",
		"confirm.deleteInbound":                         "Удалить подключение {name}?",
		"routing.title":                                 "Правила маршрутизации",
		"routing.summaryStart":                          "Просмотр, создание, обновление и удаление правил через",
		"routing.add":                                   "Добавить правило маршрутизации",
		"routing.edit":                                  "Изменить правило маршрутизации",
		"routing.addRule":                               "Добавить правило",
		"routing.save":                                  "Сохранить правило",
		"routing.delete":                                "Удалить правило",
		"routing.nameRequired":                          "Укажите имя правила маршрутизации",
		"routing.empty":                                 "Нажмите «Обновить» или загрузите правила маршрутизации.",
		"routing.match":                                 "Условие",
		"routing.outbound":                              "Направление",
		"routing.presets":                               "Готовые наборы",
		"routing.applyPreset":                           "Применить готовый набор",
		"routing.loadPresets":                           "Загрузить API наборов",
		"routing.loadRaw":                               "Загрузить исходный ответ API",
		"routing.matchRule":                             "Условие маршрута",
		"routing.geoStart":                              "Российские данные geo/site загружаются из",
		"routing.geoEnd":                                "при применении профиля с учётом России.",
		"routing.clearConsole":                          "Очистить консоль",
		"confirm.deleteRoutingRule":                     "Удалить правило маршрутизации {name}?",
		"clientLinks.title":                             "Ссылки клиентов",
		"clientLinks.generateCurrent":                   "Создать текущие",
		"clientLinks.load":                              "Загрузить ссылки клиентов",
		"clientLinks.openExport":                        "Открыть QR и экспорт",
		"clientLinks.loadBase64":                        "Загрузить подписку base64",
		"clientLinks.loadRaw":                           "Загрузить исходную подписку",
		"clientLinks.downloadJSON":                      "Скачать JSON ссылок",
		"clientLinks.downloadBase64":                    "Скачать подписку base64",
		"clientLinks.downloadRaw":                       "Скачать исходную подписку",
		"clientLinks.downloadClientConfigs":             "Скачать клиентские конфигурации",
		"clientLinks.copyOutput":                        "Копировать результат",
		"clientLinks.qrPrivacy":                         "QR-коды создаются локально API панели; строки подключения не отправляются сторонним сервисам.",
		"clientLinks.modalSummary":                      "Копируйте, скачивайте или сканируйте строки подключения ниже. QR-изображения создаются через",
		"clientLinks.loading":                           "Загрузка ссылок подключения...",
		"clientLinks.failed":                            "Не удалось загрузить ссылки",
		"clientLinks.empty":                             "Для этого подключения нет ссылок. Убедитесь, что оно включено, а общие настройки сохранены.",
		"clientLinks.loadingClientConfigs":              "Загрузка клиентских конфигураций...",
		"clientLinks.noClientConfigs":                   "Клиентских конфигураций нет",
		"clientLinks.downloaded":                        "Скачан файл {filename}",
		"clientLinks.clientConfigsFailed":               "Не удалось скачать клиентские конфигурации: {error}",
		"clientLinks.downloadingJSON":                   "Скачивание JSON ссылок клиентов...",
		"clientLinks.downloading":                       "Скачивание {path}...",
		"clientLinks.copiedOutput":                      "Скопировано в буфер обмена",
		"clientLinks.copyFailed":                        "Ошибка копирования: {error}",
		"clientLinks.port":                              "Порт {port}",
		"clientLinks.copyFailedAlert":                   "Не удалось скопировать ссылку: {error}",
		"clientLinks.qrAlt":                             "QR-код ссылки клиента",
		"clientLinks.qrFailed":                          "Не удалось создать QR-код: {error}",
		"clientLinks.connectionTitle":                   "Ссылки для подключения клиентов",
		"clientLinks.inboundTitle":                      "Ссылки клиентов: {name}",
		"clientLinks.showQR":                            "Показать QR",
		"clientLinks.renderingQR":                       "Создание QR...",
		"clientLinks.nothingToCopy":                     "Пока нечего копировать",
		"clientLinks.copied":                            "Скопировано!",
		"modal.addInbound":                              "Добавить подключение",
		"modal.closeSymbol":                             "×",
		"settings.title":                                "Настройки",
		"settings.panelAccess":                          "Доступ к панели",
		"settings.panelListen":                          "Адрес панели",
		"settings.webBasePath":                          "Базовый путь панели",
		"settings.mode":                                 "Режим",
		"settings.domain":                               "Домен",
		"settings.email":                                "Email",
		"settings.masqueradeURL":                        "URL маскировки",
		"settings.fallbackRoot":                         "Резервный каталог",
		"settings.load":                                 "Загрузить настройки",
		"settings.save":                                 "Сохранить настройки",
		"runtime.systemResources":                       "Ресурсы системы",
		"runtime.refreshTelemetry":                      "Обновить телеметрию",
		"runtime.load":                                  "Нагрузка",
		"runtime.ram":                                   "ОЗУ",
		"runtime.disk":                                  "Диск",
		"runtime.telemetrySummary":                      "CPU, память, диск и средняя нагрузка из",
		"runtime.rawJSON":                               "Исходный JSON",
		"runtime.cpuUsage":                              "Использование CPU",
		"runtime.memoryUsage":                           "Использование памяти",
		"runtime.diskSpace":                             "Дисковое пространство",
		"runtime.networkInterfaces":                     "Сетевые интерфейсы",
		"runtime.networkSummary":                        "Принятые и отправленные байты и пакеты из",
		"runtime.interface":                             "Интерфейс",
		"runtime.bytesReceived":                         "Принято байт (RX)",
		"runtime.bytesTransmitted":                      "Отправлено байт (TX)",
		"runtime.packets":                               "Пакеты (RX / TX)",
		"runtime.noInterfaces":                          "Интерфейсы не загружены. Нажмите «Обновить».",
		"runtime.loadNetwork":                           "Загрузить статистику сети",
		"runtime.managedProcesses":                      "Управляемые процессы",
		"runtime.processesSummary":                      "Процессы управляемых сервисов из",
		"runtime.pid":                                   "PID",
		"runtime.cpuPercent":                            "CPU %",
		"runtime.memoryRSS":                             "Память (RSS)",
		"runtime.uptime":                                "Время работы",
		"runtime.noProcesses":                           "Процессы не загружены.",
		"runtime.loadProcesses":                         "Загрузить процессы",
		"runtime.listeningPorts":                        "Прослушиваемые порты",
		"runtime.connectionsSummary":                    "Прослушиваемые TCP/UDP-сокеты из",
		"runtime.loadConnections":                       "Загрузить подключения",
		"runtime.diskUsage":                             "Использование диска",
		"runtime.diskSummary":                           "Размеры каталогов Veil из",
		"runtime.loadDisk":                              "Загрузить использование диска",
		"service.status":                                "Состояние служб",
		"service.loadStatus":                            "Загрузить состояние",
		"service.autoRefreshOff":                        "Автообновление: ВЫКЛ",
		"service.autoRefreshOn":                         "Автообновление: вкл. (10 с)",
		"telemetry.autoRefreshOff":                      "Автообновление: выкл.",
		"telemetry.autoRefreshOn":                       "Автообновление: вкл. (1 с)",
		"service.restart":                               "Перезапустить {service}",
		"warp.title":                                    "Состояние интеграции WARP",
		"warp.summary":                                  "Настройка необязательного WireGuard/WARP-сервиса sing-box через",
		"warp.redactedSummary":                          "Скрытые приватный ключ и лицензия сохраняются API при отправке как",
		"warp.enabledHelp":                              "Включить или выключить фоновый сервис WireGuard/WARP",
		"warp.connectionSettings":                       "Параметры подключения",
		"warp.credentials":                              "Учётные данные",
		"warp.proxyRouting":                             "Прокси и маршрутизация",
		"warp.endpoint":                                 "Конечная точка",
		"warp.privateKey":                               "Приватный ключ WireGuard",
		"warp.privateKeyShort":                          "Приватный ключ",
		"warp.peerKey":                                  "Публичный ключ узла",
		"warp.license":                                  "Необязательная лицензия WARP+",
		"warp.licenseKey":                               "Ключ лицензии",
		"warp.localAddress":                             "Локальный адрес",
		"warp.reserved":                                 "Зарезервированные байты",
		"warp.socksListen":                              "Адрес SOCKS",
		"warp.socksPort":                                "Порт SOCKS",
		"warp.load":                                     "Загрузить WARP",
		"warp.save":                                     "Сохранить конфигурацию WARP",
	})

	catalog := protocols.NewCatalog()
	enList := catalog.DisplayNameList()
	names := make([]string, 0, len(catalog.Choices()))
	for _, choice := range catalog.Choices() {
		names = append(names, choice.DisplayName)
	}
	ruList := russianList(names)
	installTranslationCatalog(LocaleEnglish, map[string]string{
		"dashboard.managementSummary": enList + " management",
		"inbounds.summary":            "Create, update, or delete " + enList + " inbound definitions through",
		"clientLinks.summary":         "Generate current " + enList + " client connection URIs/client config artifacts from saved settings and enabled inbounds through",
	})
	installTranslationCatalog(LocaleRussian, map[string]string{
		"dashboard.managementSummary": "Управление " + ruList,
		"inbounds.summary":            "Создание, обновление и удаление подключений " + ruList + " через",
		"clientLinks.summary":         "Создание URI и клиентских конфигураций " + ruList + " из сохранённых настроек и включённых подключений через",
	})
}

func russianList(values []string) string {
	switch len(values) {
	case 0:
		return ""
	case 1:
		return values[0]
	case 2:
		return values[0] + " и " + values[1]
	default:
		out := ""
		for i, value := range values {
			if i > 0 {
				if i == len(values)-1 {
					out += " и "
				} else {
					out += ", "
				}
			}
			out += value
		}
		return out
	}
}

func installTranslationCatalog(locale string, entries map[string]string) {
	catalog := translationCatalogs[locale]
	for key, value := range entries {
		catalog[key] = value
	}
}
