#!/usr/bin/env python3
"""Generate the handwritten streaming extension beside oapi-codegen output."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TEMPLATE = ROOT / "sdk/go/veilclient_streaming.tmpl"
OUTPUT = ROOT / "sdk/go/veilclient_streaming.gen.go"
HEADER = "// Code generated by scripts/generate-go-sdk-streaming.py; DO NOT EDIT.\n\n"

OUTPUT.write_text(HEADER + TEMPLATE.read_text(encoding="utf-8"), encoding="utf-8")
