import { createRouter, RouterProvider } from "@tanstack/react-router";
import { routeTree } from "./routeTree.gen";

// The router basepath matches the panel WebBasePath so client-side nav works
// under "/<secret>" too. Read from the <base href> the server rewrites.
function routerBasepath(): string {
	const el = document.querySelector("base");
	const href = el?.getAttribute("href") ?? "/";
	return href.endsWith("/") && href.length > 1 ? href.slice(0, -1) : href;
}

// S7: file-based router. routeTree.gen.ts is generated by
// @tanstack/router-plugin from src/routes/** (typed params + search).
const router = createRouter({
	routeTree,
	basepath: routerBasepath(),
});

declare module "@tanstack/react-router" {
	interface Register {
		router: typeof router;
	}
}

export function RouterView() {
	return <RouterProvider router={router} />;
}
